(in-package #:bitcoin-lisp.rpc)

;;;; Tables GENERATED from Bitcoin Core's sources -- do not hand-edit.
;;;
;;; Three tables the RPC server consults for every call, each derived from
;;; Core by a script and cross-checked against Core's client.cpp by
;;; rpc-tests: *RPC-ARG-CONVERSIONS* (which positional arguments are JSON,
;;; from client.cpp's vRPCConvertParams), *RPC-NAMED-ONLY-ARGS* (members of
;;; an OBJ_NAMED_PARAMS options object) and *RPC-NAMED-ARG-NAMES* (every
;;; method's positional argument names, from the RPCHelpMan declarations;
;;; scripts/gen-rpc-arg-names.py). They are data: a Core upgrade means
;;; rerunning the scripts against refs/bitcoin, not editing rows. Kept apart
;;; from the handlers on purpose (refactoring plan, P2d-2 cancelled).

(defparameter *rpc-arg-conversions*
  '(
    ("addconnection" (2 "v2transport" . nil))
    ("addnode" (2 "v2transport" . nil))
    ("addpeeraddress" (1 "port" . nil) (2 "tried" . nil))
    ("analyzepsbt" (0 "psbt" . t))
    ("backupwallet" (0 "destination" . t))
    ("bumpfee" (1 "conf_target" . nil) (1 "fee_rate" . nil) (1 "options" . nil) (1 "original_change_index" . nil) (1 "outputs" . nil) (1 "replaceable" . nil))
    ("combinepsbt" (0 "txs" . nil))
    ("combinerawtransaction" (0 "txs" . nil))
    ("converttopsbt" (1 "permitsigdata" . nil) (2 "iswitness" . nil))
    ("createmultisig" (0 "nrequired" . nil) (1 "keys" . nil))
    ("createpsbt" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "replaceable" . nil) (4 "version" . nil))
    ("createrawtransaction" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "replaceable" . nil) (4 "version" . nil))
    ("createwallet" (0 "wallet_name" . t) (1 "disable_private_keys" . nil) (2 "blank" . nil) (3 "passphrase" . t) (4 "avoid_reuse" . nil) (5 "descriptors" . nil) (6 "load_on_startup" . nil) (7 "external_signer" . nil))
    ("createwalletdescriptor" (1 "internal" . nil) (1 "options" . nil))
    ("decodepsbt" (0 "psbt" . t))
    ("decoderawtransaction" (1 "iswitness" . nil))
    ("deriveaddresses" (1 "range" . nil))
    ("descriptorprocesspsbt" (0 "psbt" . t) (1 "descriptors" . nil) (2 "sighashtype" . t) (3 "bip32derivs" . nil) (4 "finalize" . nil))
    ("disconnectnode" (1 "nodeid" . nil))
    ("dumptxoutset" (0 "path" . t) (1 "type" . t) (2 "options" . nil) (2 "rollback" . nil))
    ("echoipc" (0 "arg" . t))
    ;; echojson's arguments are declared STR in Core's RPCHelpMan (with
    ;; skip_type_check, rpc/node.cpp:286-295), so dumpArgMap reports them as
    ;; string-typed even though client.cpp lists them as convertible -- the one
    ;; row where the two Core tables deliberately disagree, which is why
    ;; rpc_help.py:72 drops echojson from the CLIENT side and compares the rest.
    ("echojson" (0 "arg0" . t) (1 "arg1" . t) (2 "arg2" . t) (3 "arg3" . t) (4 "arg4" . t) (5 "arg5" . t) (6 "arg6" . t) (7 "arg7" . t) (8 "arg8" . t) (9 "arg9" . t))
    ("encryptwallet" (0 "passphrase" . t))
    ("estimaterawfee" (0 "conf_target" . nil) (1 "threshold" . nil))
    ("estimatesmartfee" (0 "conf_target" . nil))
    ("finalizepsbt" (0 "psbt" . t) (1 "extract" . nil))
    ("fundrawtransaction" (1 "add_inputs" . nil) (1 "changePosition" . nil) (1 "conf_target" . nil) (1 "feeRate" . nil) (1 "fee_rate" . nil) (1 "includeWatching" . nil) (1 "include_unsafe" . nil) (1 "input_weights" . nil) (1 "lockUnspents" . nil) (1 "max_tx_weight" . nil) (1 "maxconf" . nil) (1 "minconf" . nil) (1 "options" . nil) (1 "replaceable" . nil) (1 "solving_data" . nil) (1 "subtractFeeFromOutputs" . nil) (2 "iswitness" . nil))
    ("generateblock" (1 "transactions" . nil) (2 "submit" . nil))
    ("generatetoaddress" (0 "nblocks" . nil) (2 "maxtries" . nil))
    ("generatetodescriptor" (0 "num_blocks" . nil) (2 "maxtries" . nil))
    ("getaddressesbylabel" (0 "label" . t))
    ("getbalance" (1 "minconf" . nil) (2 "include_watchonly" . nil) (3 "avoid_reuse" . nil))
    ("getblock" (1 "verbose" . nil) (1 "verbosity" . nil))
    ("getblockfrompeer" (1 "peer_id" . nil))
    ("getblockhash" (0 "height" . nil))
    ("getblockheader" (1 "verbose" . nil))
    ("getblockstats" (0 "hash_or_height" . nil) (1 "stats" . nil))
    ("getblocktemplate" (0 "template_request" . nil))
    ("getchaintxstats" (0 "nblocks" . nil))
    ("getdescriptoractivity" (0 "blockhashes" . nil) (1 "scanobjects" . nil) (2 "include_mempool" . nil))
    ("gethdkeys" (0 "active_only" . nil) (0 "options" . nil) (0 "private" . nil))
    ("getmempoolancestors" (1 "verbose" . nil))
    ("getmempooldescendants" (1 "verbose" . nil))
    ("getnetworkhashps" (0 "nblocks" . nil) (1 "height" . nil))
    ("getnewaddress" (0 "label" . t) (1 "address_type" . t))
    ("getnodeaddresses" (0 "count" . nil))
    ("getorphantxs" (0 "verbosity" . nil))
    ("getrawmempool" (0 "verbose" . nil) (1 "mempool_sequence" . nil))
    ("getrawtransaction" (1 "verbose" . nil) (1 "verbosity" . nil))
    ("getreceivedbyaddress" (1 "minconf" . nil) (2 "include_immature_coinbase" . nil))
    ("getreceivedbylabel" (0 "label" . t) (1 "minconf" . nil) (2 "include_immature_coinbase" . nil))
    ("gettransaction" (1 "include_watchonly" . nil) (2 "verbose" . nil))
    ("gettxout" (1 "n" . nil) (2 "include_mempool" . nil))
    ("gettxoutproof" (0 "txids" . nil))
    ("gettxoutsetinfo" (1 "hash_or_height" . nil) (2 "use_index" . nil))
    ("gettxspendingprevout" (0 "outputs" . nil) (1 "mempool_only" . nil) (1 "options" . nil) (1 "return_spending_tx" . nil))
    ("importdescriptors" (0 "requests" . nil))
    ("importmempool" (0 "filepath" . t) (1 "apply_fee_delta_priority" . nil) (1 "apply_unbroadcast_set" . nil) (1 "options" . nil) (1 "use_current_time" . nil))
    ("joinpsbts" (0 "txs" . nil))
    ("keypoolrefill" (0 "newsize" . nil))
    ("listdescriptors" (0 "private" . nil))
    ("listreceivedbyaddress" (0 "minconf" . nil) (1 "include_empty" . nil) (2 "include_watchonly" . nil) (4 "include_immature_coinbase" . nil))
    ("listreceivedbylabel" (0 "minconf" . nil) (1 "include_empty" . nil) (2 "include_watchonly" . nil) (3 "include_immature_coinbase" . nil))
    ("listsinceblock" (0 "blockhash" . t) (1 "target_confirmations" . nil) (2 "include_watchonly" . nil) (3 "include_removed" . nil) (4 "include_change" . nil) (5 "label" . t))
    ("listtransactions" (0 "label" . t) (1 "count" . nil) (2 "skip" . nil) (3 "include_watchonly" . nil))
    ("listunspent" (0 "minconf" . nil) (1 "maxconf" . nil) (2 "addresses" . nil) (3 "include_unsafe" . nil) (4 "include_immature_coinbase" . nil) (4 "maximumAmount" . nil) (4 "maximumCount" . nil) (4 "minimumAmount" . nil) (4 "minimumSumAmount" . nil) (4 "query_options" . nil))
    ("loadtxoutset" (0 "path" . t))
    ("loadwallet" (0 "filename" . t) (1 "load_on_startup" . nil))
    ("lockunspent" (0 "unlock" . nil) (1 "transactions" . nil) (2 "persistent" . nil))
    ("logging" (0 "include" . nil) (1 "exclude" . nil))
    ("prioritisetransaction" (1 "dummy" . nil) (2 "fee_delta" . nil))
    ("pruneblockchain" (0 "height" . nil))
    ("psbtbumpfee" (1 "conf_target" . nil) (1 "fee_rate" . nil) (1 "options" . nil) (1 "original_change_index" . nil) (1 "outputs" . nil) (1 "replaceable" . nil))
    ("rescanblockchain" (0 "start_height" . nil) (1 "stop_height" . nil))
    ("restorewallet" (0 "wallet_name" . t) (1 "backup_file" . t) (2 "load_on_startup" . nil))
    ("scanblocks" (1 "scanobjects" . nil) (2 "start_height" . nil) (3 "stop_height" . nil) (5 "filter_false_positives" . nil) (5 "options" . nil))
    ("scantxoutset" (1 "scanobjects" . nil))
    ("send" (0 "outputs" . nil) (1 "conf_target" . nil) (3 "fee_rate" . nil) (4 "add_inputs" . nil) (4 "add_to_wallet" . nil) (4 "change_position" . nil) (4 "conf_target" . nil) (4 "fee_rate" . nil) (4 "include_unsafe" . nil) (4 "include_watching" . nil) (4 "inputs" . nil) (4 "lock_unspents" . nil) (4 "locktime" . nil) (4 "max_tx_weight" . nil) (4 "maxconf" . nil) (4 "minconf" . nil) (4 "options" . nil) (4 "psbt" . nil) (4 "replaceable" . nil) (4 "solving_data" . nil) (4 "subtract_fee_from_outputs" . nil) (5 "version" . nil))
    ("sendall" (0 "recipients" . nil) (1 "conf_target" . nil) (3 "fee_rate" . nil) (4 "add_to_wallet" . nil) (4 "conf_target" . nil) (4 "fee_rate" . nil) (4 "include_watching" . nil) (4 "inputs" . nil) (4 "lock_unspents" . nil) (4 "locktime" . nil) (4 "maxconf" . nil) (4 "minconf" . nil) (4 "options" . nil) (4 "psbt" . nil) (4 "replaceable" . nil) (4 "send_max" . nil) (4 "solving_data" . nil) (4 "version" . nil))
    ("sendmany" (0 "dummy" . t) (1 "amounts" . nil) (2 "minconf" . nil) (3 "comment" . t) (4 "subtractfeefrom" . nil) (5 "replaceable" . nil) (6 "conf_target" . nil) (7 "estimate_mode" . t) (8 "fee_rate" . nil) (9 "verbose" . nil))
    ("sendmsgtopeer" (0 "peer_id" . nil))
    ("sendrawtransaction" (1 "maxfeerate" . nil) (2 "maxburnamount" . nil))
    ("sendtoaddress" (0 "address" . t) (1 "amount" . nil) (2 "comment" . t) (3 "comment_to" . t) (4 "subtractfeefromamount" . nil) (5 "replaceable" . nil) (6 "conf_target" . nil) (7 "estimate_mode" . t) (8 "avoid_reuse" . nil) (9 "fee_rate" . nil) (10 "verbose" . nil))
    ("setban" (2 "bantime" . nil) (3 "absolute" . nil))
    ("setlabel" (1 "label" . t))
    ("mockscheduler" (0 "delta_time" . nil))
    ("setmocktime" (0 "timestamp" . nil))
    ("setnetworkactive" (0 "state" . nil))
    ("setwalletflag" (1 "value" . nil))
    ("signmessage" (1 "message" . t))
    ("signmessagewithprivkey" (1 "message" . t))
    ("signrawtransactionwithkey" (1 "privkeys" . nil) (2 "prevtxs" . nil))
    ("signrawtransactionwithwallet" (1 "prevtxs" . nil))
    ("simulaterawtransaction" (0 "rawtxs" . nil) (1 "include_watchonly" . nil) (1 "options" . nil))
    ("stop" (0 "wait" . nil))
    ("submitpackage" (0 "package" . nil) (1 "maxfeerate" . nil) (2 "maxburnamount" . nil))
    ("testmempoolaccept" (0 "rawtxs" . nil) (1 "maxfeerate" . nil))
    ("unloadwallet" (0 "wallet_name" . t) (1 "load_on_startup" . nil))
    ("utxoupdatepsbt" (0 "psbt" . t) (1 "descriptors" . nil))
    ("verifychain" (0 "checklevel" . nil) (1 "nblocks" . nil))
    ("verifymessage" (1 "signature" . t) (2 "message" . t))
    ("waitforblock" (1 "timeout" . nil))
    ("waitforblockheight" (0 "height" . nil) (1 "timeout" . nil))
    ("waitfornewblock" (0 "timeout" . nil))
    ("walletcreatefundedpsbt" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "add_inputs" . nil) (3 "changePosition" . nil) (3 "conf_target" . nil) (3 "feeRate" . nil) (3 "fee_rate" . nil) (3 "includeWatching" . nil) (3 "include_unsafe" . nil) (3 "lockUnspents" . nil) (3 "max_tx_weight" . nil) (3 "maxconf" . nil) (3 "minconf" . nil) (3 "options" . nil) (3 "replaceable" . nil) (3 "solving_data" . nil) (3 "subtractFeeFromOutputs" . nil) (4 "bip32derivs" . nil) (5 "version" . nil))
    ("walletpassphrase" (0 "passphrase" . t) (1 "timeout" . nil))
    ("walletpassphrasechange" (0 "oldpassphrase" . t) (1 "newpassphrase" . t))
    ("walletprocesspsbt" (0 "psbt" . t) (1 "sign" . nil) (2 "sighashtype" . t) (3 "bip32derivs" . nil) (4 "finalize" . nil)))
  "Per method, the (POSITION NAME . STRING-P) of every argument Core classifies
in src/rpc/client.cpp's vRPCConvertParams.

STRING-P is Core's `type == STR || type == STR_HEX` (RPCHelpMan::GetArgMap,
rpc/util.cpp:837-844) — TRUE means the argument is passed through as a string,
FALSE means a JSON-RPC client must parse it before sending. That distinction is
the whole content of the table, and it is what `bitcoin-cli` gets wrong if the
two implementations disagree.

GENERATED from Core's own client.cpp, restricted to the methods this node
implements, and kept honest by RPC-ARG-CONVERSIONS-MATCH-CORE, which re-parses
that file and compares. Editing an entry here by hand without changing Core is
how the two drift apart, so the test exists to make that impossible to do
quietly.")

;;; Members of an RPC's OBJ_NAMED_PARAMS options object, which Core lets a
;;; client pass as TOP-LEVEL named arguments.
;;;
;;; RPCHelpMan::GetArgNames emits these with named_only=true (rpc/util.cpp:750) and
;;; transformNamedArguments collects them into a fresh options object which it
;;; pushes at the options slot (rpc/server.cpp:408-415). Without them the server
;;; answers "Unknown named parameter fee_rate" to a call every Core client can
;;; make.
;;;
;;; ⚠️ Covers BOTH declaration forms. Matching only `RPCHelpMan{"name"` misses
;;; every RPC declared through a helper that takes the name as a PARAMETER —
;;; bumpfee and psbtbumpfee are declared that way (wallet/rpc/spend.cpp:960,
;;; 1166-1167), so both were absent and wallet_bumpfee.py died on fee_rate.
;;;
;;; ⚠️ The rows are the DIRECT members of the OBJ_NAMED_PARAMS argument, and
;;; every one of them. GetArgNames walks `arg.m_inner' and goes no deeper, so a
;;; member of a member (subtractFeeFromOutputs' vout_index, input_weights'
;;; txid/vout/weight) is NOT a named-only argument; and the members Core
;;; appends from a helper (FundTxDoc's conf_target, estimate_mode, replaceable,
;;; solving_data, spliced in with Cat<>) are. An earlier reading of this table
;;; had both errors at once: it listed the nested names and dropped every
;;; camelCase one — changeAddress, changePosition, includeWatching,
;;; lockUnspents, feeRate, subtractFeeFromOutputs — so wallet_keypool.py:165,
;;; which calls walletcreatefundedpsbt(feeRate=..., subtractFeeFromOutputs=...),
;;; got "Unknown named parameter feeRate".
;;;
;;; GENERATED from Core's RPCHelpMan declarations. Do not hand-edit.
(setf *rpc-named-only-args*
  '(
    ("bumpfee" "conf_target" "fee_rate" "replaceable" "estimate_mode" "outputs" "original_change_index")
    ("createwalletdescriptor" "internal" "hdkey")
    ("dumptxoutset" "rollback")
    ("fundrawtransaction" "add_inputs" "include_unsafe" "minconf" "maxconf" "changeAddress" "changePosition" "change_type" "includeWatching" "lockUnspents" "fee_rate" "feeRate" "subtractFeeFromOutputs" "input_weights" "max_tx_weight" "conf_target" "estimate_mode" "replaceable" "solving_data")
    ("gethdkeys" "active_only" "private")
    ("gettxspendingprevout" "mempool_only" "return_spending_tx")
    ("importmempool" "use_current_time" "apply_fee_delta_priority" "apply_unbroadcast_set")
    ("listunspent" "minimumAmount" "maximumAmount" "maximumCount" "minimumSumAmount" "include_immature_coinbase")
    ("psbtbumpfee" "conf_target" "fee_rate" "replaceable" "estimate_mode" "outputs" "original_change_index")
    ("scanblocks" "filter_false_positives")
    ("send" "add_inputs" "include_unsafe" "minconf" "maxconf" "add_to_wallet" "change_address" "change_position" "change_type" "fee_rate" "include_watching" "inputs" "locktime" "lock_unspents" "psbt" "subtract_fee_from_outputs" "max_tx_weight" "conf_target" "estimate_mode" "replaceable" "solving_data")
    ("sendall" "add_to_wallet" "fee_rate" "include_watching" "inputs" "locktime" "lock_unspents" "psbt" "send_max" "minconf" "maxconf" "version" "conf_target" "estimate_mode" "replaceable" "solving_data")
    ("simulaterawtransaction" "include_watchonly")
    ("walletcreatefundedpsbt" "add_inputs" "include_unsafe" "minconf" "maxconf" "changeAddress" "changePosition" "change_type" "includeWatching" "lockUnspents" "fee_rate" "feeRate" "subtractFeeFromOutputs" "max_tx_weight" "conf_target" "estimate_mode" "replaceable" "solving_data")))

;;; Positional argument names for every RPC method Core declares, in declaration
;;; order — what transformNamedArguments (rpc/server.cpp:396) matches an incoming
;;; named parameter against. A name containing #\\| lists aliases for one slot,
;;; exactly as Core stores it; getblock's "verbosity|verbose" is the case that
;;; matters, since older clients send the second spelling.
;;;
;;; GENERATED from Core's RPCHelpMan declarations by scripts/gen-rpc-arg-names.py,
;;; which walks src/rpc/*.cpp and src/wallet/rpc/*.cpp. Do not hand-edit: rerun the
;;; script against refs/bitcoin.
;;;
;;; It has to come from RPCHelpMan and not from client.cpp, which is where the earlier
;;; type-conversion table comes from. client.cpp lists only arguments that need
;;; JSON CONVERSION, so it structurally omits every STRING argument. A named-parameter
;;; table derived from it is missing `scantxoutset action`, `setban subnet`,
;;; `addnode command`, and about a hundred more — and, worse, the positions of the
;;; arguments that ARE listed are Core's real positions, so a table built from it
;;; disagrees with itself about where an argument sits.
;;;
;;; The hand-curated 43-method predecessor is why this exists. MiniWallet — which a
;;; large share of Core's functional suite instantiates — opens with
;;; `scantxoutset(action="start", ...)`, and `action` was not in the table, so
;;; the node answered "Unknown named parameter action" and the test died in
;;; setup. Found by running the suite, not by reading it.
(setf *rpc-named-arg-names*
  '(
    ("abandontransaction" "txid")
    ("abortprivatebroadcast" "id")
    ("abortrescan")
    ("addconnection" "address" "connection_type" "v2transport")
    ("addnode" "node" "command" "v2transport")
    ("addpeeraddress" "address" "port" "tried")
    ("analyzepsbt" "psbt")
    ("backupwallet" "destination")
    ("bumpfee" "txid" "options")
    ("clearbanned")
    ("combinepsbt" "txs")
    ("combinerawtransaction" "txs")
    ("converttopsbt" "hexstring" "permitsigdata" "iswitness")
    ("createmultisig" "nrequired" "keys" "address_type")
    ("createpsbt" "inputs" "outputs" "locktime" "replaceable" "version")
    ("createrawtransaction" "inputs" "outputs" "locktime" "replaceable" "version")
    ("createwallet" "wallet_name" "disable_private_keys" "blank" "passphrase" "avoid_reuse" "descriptors" "load_on_startup" "external_signer")
    ("createwalletdescriptor" "type" "options")
    ("decodepsbt" "psbt")
    ("decoderawtransaction" "hexstring" "iswitness")
    ("decodescript" "hexstring")
    ("deriveaddresses" "descriptor" "range")
    ("descriptorprocesspsbt" "psbt" "descriptors" "sighashtype" "bip32derivs" "finalize")
    ("disconnectnode" "address" "nodeid")
    ("dumptxoutset" "path" "type" "options")
    ("echo" "arg0" "arg1" "arg2" "arg3" "arg4" "arg5" "arg6" "arg7" "arg8" "arg9")
    ("echoipc" "arg")
    ("echojson" "arg0" "arg1" "arg2" "arg3" "arg4" "arg5" "arg6" "arg7" "arg8" "arg9")
    ("encryptwallet" "passphrase")
    ("enumeratesigners")
    ("estimaterawfee" "conf_target" "threshold")
    ("estimatesmartfee" "conf_target" "estimate_mode")
    ("finalizepsbt" "psbt" "extract")
    ("fundrawtransaction" "hexstring" "options" "iswitness")
    ("generate")
    ("generateblock" "output" "transactions" "submit")
    ("generatetoaddress" "nblocks" "address" "maxtries")
    ("generatetodescriptor" "num_blocks" "descriptor" "maxtries")
    ("getaddednodeinfo" "node")
    ("getaddressesbylabel" "label")
    ("getaddressinfo" "address")
    ("getaddrmaninfo")
    ("getbalance" "dummy" "minconf" "include_watchonly" "avoid_reuse")
    ("getbalances")
    ("getbestblockhash")
    ("getblock" "blockhash" "verbosity|verbose")
    ("getblockchaininfo")
    ("getblockcount")
    ("getblockfilter" "blockhash" "filtertype")
    ("getblockfrompeer" "blockhash" "peer_id")
    ("getblockhash" "height")
    ("getblockheader" "blockhash" "verbose")
    ("getblockstats" "hash_or_height" "stats")
    ("getblocktemplate" "template_request")
    ("getchainstates")
    ("getchaintips")
    ("getchaintxstats" "nblocks" "blockhash")
    ("getconnectioncount")
    ("getdeploymentinfo" "blockhash")
    ("getdescriptoractivity" "blockhashes" "scanobjects" "include_mempool")
    ("getdescriptorinfo" "descriptor")
    ("getdifficulty")
    ("gethdkeys" "options")
    ("getindexinfo" "index_name")
    ("getmemoryinfo" "mode")
    ("getmempoolancestors" "txid" "verbose")
    ("getmempoolcluster" "txid")
    ("getmempooldescendants" "txid" "verbose")
    ("getmempoolentry" "txid")
    ("getmempoolfeeratediagram")
    ("getmempoolinfo")
    ("getmininginfo")
    ("getnettotals")
    ("getnetworkhashps" "nblocks" "height")
    ("getnetworkinfo")
    ("getnewaddress" "label" "address_type")
    ("getnodeaddresses" "count" "network")
    ("getorphantxs" "verbosity")
    ("getpeerinfo")
    ("getprioritisedtransactions")
    ("getprivatebroadcastinfo")
    ("getrawaddrman")
    ("getrawchangeaddress" "address_type")
    ("getrawmempool" "verbose" "mempool_sequence")
    ("getrawtransaction" "txid" "verbosity|verbose" "blockhash")
    ("getreceivedbyaddress" "address" "minconf" "include_immature_coinbase")
    ("getreceivedbylabel" "label" "minconf" "include_immature_coinbase")
    ("getrpcinfo")
    ("gettransaction" "txid" "include_watchonly" "verbose")
    ("gettxout" "txid" "n" "include_mempool")
    ("gettxoutproof" "txids" "blockhash")
    ("gettxoutsetinfo" "hash_type" "hash_or_height" "use_index")
    ("gettxspendingprevout" "outputs" "options")
    ("getwalletinfo")
    ("getzmqnotifications")
    ("help" "command")
    ("importdescriptors" "requests")
    ("importmempool" "filepath" "options")
    ("importprunedfunds" "rawtransaction" "txoutproof")
    ("invalidateblock" "blockhash")
    ("joinpsbts" "txs")
    ("keypoolrefill" "newsize")
    ("listaddressgroupings")
    ("listbanned")
    ("listdescriptors" "private")
    ("listlabels" "purpose")
    ("listlockunspent")
    ("listreceivedbyaddress" "minconf" "include_empty" "include_watchonly" "address_filter" "include_immature_coinbase")
    ("listreceivedbylabel" "minconf" "include_empty" "include_watchonly" "include_immature_coinbase")
    ("listsinceblock" "blockhash" "target_confirmations" "include_watchonly" "include_removed" "include_change" "label")
    ("listtransactions" "label" "count" "skip" "include_watchonly")
    ("listunspent" "minconf" "maxconf" "addresses" "include_unsafe" "query_options")
    ("listwalletdir")
    ("listwallets")
    ("loadtxoutset" "path")
    ("loadwallet" "filename" "load_on_startup")
    ("lockunspent" "unlock" "transactions" "persistent")
    ("logging" "include" "exclude")
    ("migratewallet" "wallet_name" "passphrase")
    ("mockscheduler" "delta_time")
    ("ping")
    ("preciousblock" "blockhash")
    ("prioritisetransaction" "txid" "dummy" "fee_delta")
    ("pruneblockchain" "height")
    ("psbtbumpfee" "txid" "options")
    ("reconsiderblock" "blockhash")
    ("removeprunedfunds" "txid")
    ("rescanblockchain" "start_height" "stop_height")
    ("restorewallet" "wallet_name" "backup_file" "load_on_startup")
    ("savemempool")
    ("scanblocks" "action" "scanobjects" "start_height" "stop_height" "filtertype" "options")
    ("scantxoutset" "action" "scanobjects")
    ("send" "outputs" "conf_target" "estimate_mode" "fee_rate" "options" "version")
    ("sendall" "recipients" "conf_target" "estimate_mode" "fee_rate" "options")
    ("sendmany" "dummy" "amounts" "minconf" "comment" "subtractfeefrom" "replaceable" "conf_target" "estimate_mode" "fee_rate" "verbose")
    ("sendmsgtopeer" "peer_id" "msg_type" "msg")
    ("sendrawtransaction" "hexstring" "maxfeerate" "maxburnamount")
    ("sendtoaddress" "address" "amount" "comment" "comment_to" "subtractfeefromamount" "replaceable" "conf_target" "estimate_mode" "avoid_reuse" "fee_rate" "verbose")
    ("setban" "subnet" "command" "bantime" "absolute")
    ("setlabel" "address" "label")
    ("setmocktime" "timestamp")
    ("setnetworkactive" "state")
    ("setwalletflag" "flag" "value")
    ("signmessage" "address" "message")
    ("signmessagewithprivkey" "privkey" "message")
    ("signrawtransactionwithkey" "hexstring" "privkeys" "prevtxs" "sighashtype")
    ("signrawtransactionwithwallet" "hexstring" "prevtxs" "sighashtype")
    ("simulaterawtransaction" "rawtxs" "options")
    ("stop" "wait")
    ("submitblock" "hexdata" "dummy")
    ("submitheader" "hexdata")
    ("submitpackage" "package" "maxfeerate" "maxburnamount")
    ("syncwithvalidationinterfacequeue")
    ("testmempoolaccept" "rawtxs" "maxfeerate")
    ("unloadwallet" "wallet_name" "load_on_startup")
    ("uptime")
    ("utxoupdatepsbt" "psbt" "descriptors")
    ("validateaddress" "address")
    ("verifychain" "checklevel" "nblocks")
    ("verifymessage" "address" "signature" "message")
    ("verifytxoutproof" "proof")
    ("waitforblock" "blockhash" "timeout")
    ("waitforblockheight" "height" "timeout")
    ("waitfornewblock" "timeout" "current_tip")
    ("walletcreatefundedpsbt" "inputs" "outputs" "locktime" "options" "bip32derivs" "version")
    ("walletdisplayaddress" "address")
    ("walletlock")
    ("walletpassphrase" "passphrase" "timeout")
    ("walletpassphrasechange" "oldpassphrase" "newpassphrase")
    ("walletprocesspsbt" "psbt" "sign" "sighashtype" "bip32derivs" "finalize")
    ))

;;; Every method's positional argument TYPES, from Core's RPCArg::Type
;;; declarations, in declaration order (scripts/gen-rpc-arg-names.py --types).
;;; NIL at a position means Core runs no gate there: an AMOUNT (a number OR a
;;; string, checked inside AmountFromValue), a RANGE (a number OR an array),
;;; or an argument declared with skip_type_check -- which is how getblock
;;; accepts a bool verbosity. A method with nothing to check has no row.
;;; CHECK-RPC-ARG-TYPES (server.lisp) is the gate that reads this.

(setf *rpc-arg-types*
  '(
    ("abandontransaction" :str-hex)
    ("abortprivatebroadcast" :str-hex)
    ("addconnection" :str :str :bool)
    ("addnode" :str :str :bool)
    ("addpeeraddress" :str :num :bool)
    ("analyzepsbt" :str)
    ("backupwallet" :str)
    ("bumpfee" :str-hex nil)
    ("combinepsbt" :arr)
    ("combinerawtransaction" :arr)
    ("converttopsbt" :str-hex :bool :bool)
    ("createmultisig" :num :arr :str)
    ("createpsbt" :arr nil :num :bool :num)
    ("createrawtransaction" :arr nil :num :bool :num)
    ("createwallet" :str :bool :bool :str :bool :bool :bool :bool)
    ("createwalletdescriptor" :str :obj-named-params)
    ("decodepsbt" :str)
    ("decoderawtransaction" :str-hex :bool)
    ("decodescript" :str-hex)
    ("deriveaddresses" :str :range)
    ("descriptorprocesspsbt" :str :arr :str :bool :bool)
    ("disconnectnode" :str :num)
    ("dumptxoutset" :str :str nil)
    ("echoipc" :str)
    ("encryptwallet" :str)
    ("estimaterawfee" :num :num)
    ("estimatesmartfee" :num :str)
    ("finalizepsbt" :str :bool)
    ("fundrawtransaction" :str-hex nil :bool)
    ("generateblock" :str :arr :bool)
    ("generatetoaddress" :num :str :num)
    ("generatetodescriptor" :num :str :num)
    ("getaddednodeinfo" :str)
    ("getaddressesbylabel" :str)
    ("getaddressinfo" :str)
    ("getbalance" :str :num :bool :bool)
    ("getblock" :str-hex nil)
    ("getblockfilter" :str-hex :str)
    ("getblockfrompeer" :str-hex :num)
    ("getblockhash" :num)
    ("getblockheader" :str-hex :bool)
    ("getblockstats" nil :arr)
    ("getblocktemplate" :obj)
    ("getchaintxstats" :num :str-hex)
    ("getdeploymentinfo" :str-hex)
    ("getdescriptoractivity" :arr :arr :bool)
    ("getdescriptorinfo" :str)
    ("gethdkeys" :obj-named-params)
    ("getindexinfo" :str)
    ("getmemoryinfo" :str)
    ("getmempoolancestors" :str-hex :bool)
    ("getmempoolcluster" :str-hex)
    ("getmempooldescendants" :str-hex :bool)
    ("getmempoolentry" :str-hex)
    ("getnetworkhashps" :num :num)
    ("getnewaddress" :str :str)
    ("getnodeaddresses" :num :str)
    ("getrawchangeaddress" :str)
    ("getrawmempool" :bool :bool)
    ("getrawtransaction" :str-hex nil :str-hex)
    ("getreceivedbyaddress" :str :num :bool)
    ("getreceivedbylabel" :str :num :bool)
    ("gettransaction" :str :bool :bool)
    ("gettxout" :str :num :bool)
    ("gettxoutproof" :arr :str-hex)
    ("gettxoutsetinfo" :str nil :bool)
    ("gettxspendingprevout" :arr :obj-named-params)
    ("help" :str)
    ("importdescriptors" :arr)
    ("importmempool" :str :obj-named-params)
    ("importprunedfunds" :str-hex :str-hex)
    ("invalidateblock" :str-hex)
    ("joinpsbts" :arr)
    ("keypoolrefill" :num)
    ("listdescriptors" :bool)
    ("listlabels" :str)
    ("listreceivedbyaddress" :num :bool :bool :str :bool)
    ("listreceivedbylabel" :num :bool :bool :bool)
    ("listsinceblock" :str :num :bool :bool :bool :str)
    ("listtransactions" :str :num :num :bool)
    ("listunspent" :num :num :arr :bool :obj-named-params)
    ("loadtxoutset" :str)
    ("loadwallet" :str :bool)
    ("lockunspent" :bool :arr :bool)
    ("logging" :arr :arr)
    ("migratewallet" :str :str)
    ("mockscheduler" :num)
    ("preciousblock" :str-hex)
    ("prioritisetransaction" :str-hex :num :num)
    ("pruneblockchain" :num)
    ("psbtbumpfee" :str-hex nil)
    ("reconsiderblock" :str-hex)
    ("removeprunedfunds" :str-hex)
    ("rescanblockchain" :num :num)
    ("restorewallet" :str :str :bool)
    ("scanblocks" :str :arr :num :num :str :obj-named-params)
    ("scantxoutset" :str :arr)
    ("send" nil :num :str :amount :obj-named-params :num)
    ("sendall" :arr :num :str :amount :obj-named-params)
    ("sendmany" :str :obj-user-keys :num :str :arr :bool :num :str :amount :bool)
    ("sendmsgtopeer" :num :str :str-hex)
    ("sendrawtransaction" :str-hex :amount :amount)
    ("sendtoaddress" :str :amount :str :str :bool :bool :num :str :bool :amount :bool)
    ("setban" :str :str :num :bool)
    ("setlabel" :str :str)
    ("setmocktime" :num)
    ("setnetworkactive" :bool)
    ("setwalletflag" :str :bool)
    ("signmessage" :str :str)
    ("signmessagewithprivkey" :str :str)
    ("signrawtransactionwithkey" :str :arr :arr :str)
    ("signrawtransactionwithwallet" :str :arr :str)
    ("simulaterawtransaction" :arr :obj-named-params)
    ("stop" :num)
    ("submitblock" :str-hex :str)
    ("submitheader" :str-hex)
    ("submitpackage" :arr :amount :amount)
    ("testmempoolaccept" :arr :amount)
    ("unloadwallet" :str :bool)
    ("utxoupdatepsbt" :str :arr)
    ("validateaddress" :str)
    ("verifychain" :num :num)
    ("verifymessage" :str :str :str)
    ("verifytxoutproof" :str-hex)
    ("waitforblock" :str-hex :num)
    ("waitforblockheight" :num :num)
    ("waitfornewblock" :num :str-hex)
    ("walletcreatefundedpsbt" :arr nil :num :obj-named-params :bool :num)
    ("walletdisplayaddress" :str)
    ("walletpassphrase" :str :num)
    ("walletpassphrasechange" :str :str)
    ("walletprocesspsbt" :str :bool :str :bool :bool)
    ))

;;; Which of every method's positional arguments Core REQUIRES: one T or NIL
;;; per position, in declaration order -- RPCArg::IsOptional() inverted, so T
;;; is a fallback spelled RPCArg::Optional::NO (rpc/util.cpp:923-930). A row
;;; with no cells is a method Core declares with no arguments.
;;;
;;; Per POSITION and not as a count, because an optional argument may sit
;;; before a required one -- prioritisetransaction (txid, dummy, fee_delta),
;;; sendmany and walletcreatefundedpsbt all do -- and then the number of
;;; required arguments is not the number a caller has to pass.
;;; CHECK-RPC-ARG-COUNT (server.lisp) runs Core's IsValidNumArgs over this row
;;; and RPC-USAGE-LINE renders the ( ) grouping of the help summary from it.
;;;
;;; GENERATED by scripts/gen-rpc-arg-names.py --required. Do not hand-edit:
;;; rerun the script against refs/bitcoin. The row LENGTH repeats what
;;; *RPC-NAMED-ARG-NAMES* already says, deliberately -- both come out of the
;;; same parse and structural-tests asserts they agree, so a regeneration that
;;; lost arguments on one side cannot pass quietly.

(setf *rpc-arg-required*
  '(
    ("abandontransaction" t)
    ("abortprivatebroadcast" t)
    ("abortrescan")
    ("addconnection" t t t)
    ("addnode" t t nil)
    ("addpeeraddress" t t nil)
    ("analyzepsbt" t)
    ("backupwallet" t)
    ("bumpfee" t nil)
    ("clearbanned")
    ("combinepsbt" t)
    ("combinerawtransaction" t)
    ("converttopsbt" t nil nil)
    ("createmultisig" t t nil)
    ("createpsbt" t t nil nil nil)
    ("createrawtransaction" t t nil nil nil)
    ("createwallet" t nil nil nil nil nil nil nil)
    ("createwalletdescriptor" t nil)
    ("decodepsbt" t)
    ("decoderawtransaction" t nil)
    ("decodescript" t)
    ("deriveaddresses" t nil)
    ("descriptorprocesspsbt" t t nil nil nil)
    ("disconnectnode" nil nil)
    ("dumptxoutset" t nil nil)
    ("echo" nil nil nil nil nil nil nil nil nil nil)
    ("echoipc" t)
    ("echojson" nil nil nil nil nil nil nil nil nil nil)
    ("encryptwallet" t)
    ("enumeratesigners")
    ("estimaterawfee" t nil)
    ("estimatesmartfee" t nil)
    ("finalizepsbt" t nil)
    ("fundrawtransaction" t nil nil)
    ("generate")
    ("generateblock" t t nil)
    ("generatetoaddress" t t nil)
    ("generatetodescriptor" t t nil)
    ("getaddednodeinfo" nil)
    ("getaddressesbylabel" t)
    ("getaddressinfo" t)
    ("getaddrmaninfo")
    ("getbalance" nil nil nil nil)
    ("getbalances")
    ("getbestblockhash")
    ("getblock" t nil)
    ("getblockchaininfo")
    ("getblockcount")
    ("getblockfilter" t nil)
    ("getblockfrompeer" t t)
    ("getblockhash" t)
    ("getblockheader" t nil)
    ("getblockstats" t nil)
    ("getblocktemplate" t)
    ("getchainstates")
    ("getchaintips")
    ("getchaintxstats" nil nil)
    ("getconnectioncount")
    ("getdeploymentinfo" nil)
    ("getdescriptoractivity" t t nil)
    ("getdescriptorinfo" t)
    ("getdifficulty")
    ("gethdkeys" nil)
    ("getindexinfo" nil)
    ("getmemoryinfo" nil)
    ("getmempoolancestors" t nil)
    ("getmempoolcluster" t)
    ("getmempooldescendants" t nil)
    ("getmempoolentry" t)
    ("getmempoolfeeratediagram")
    ("getmempoolinfo")
    ("getmininginfo")
    ("getnettotals")
    ("getnetworkhashps" nil nil)
    ("getnetworkinfo")
    ("getnewaddress" nil nil)
    ("getnodeaddresses" nil nil)
    ("getorphantxs" nil)
    ("getpeerinfo")
    ("getprioritisedtransactions")
    ("getprivatebroadcastinfo")
    ("getrawaddrman")
    ("getrawchangeaddress" nil)
    ("getrawmempool" nil nil)
    ("getrawtransaction" t nil nil)
    ("getreceivedbyaddress" t nil nil)
    ("getreceivedbylabel" t nil nil)
    ("getrpcinfo")
    ("gettransaction" t nil nil)
    ("gettxout" t t nil)
    ("gettxoutproof" t nil)
    ("gettxoutsetinfo" nil nil nil)
    ("gettxspendingprevout" t nil)
    ("getwalletinfo")
    ("getzmqnotifications")
    ("help" nil)
    ("importdescriptors" t)
    ("importmempool" t nil)
    ("importprunedfunds" t t)
    ("invalidateblock" t)
    ("joinpsbts" t)
    ("keypoolrefill" nil)
    ("listaddressgroupings")
    ("listbanned")
    ("listdescriptors" nil)
    ("listlabels" nil)
    ("listlockunspent")
    ("listreceivedbyaddress" nil nil nil nil nil)
    ("listreceivedbylabel" nil nil nil nil)
    ("listsinceblock" nil nil nil nil nil nil)
    ("listtransactions" nil nil nil nil)
    ("listunspent" nil nil nil nil nil)
    ("listwalletdir")
    ("listwallets")
    ("loadtxoutset" t)
    ("loadwallet" t nil)
    ("lockunspent" t nil nil)
    ("logging" nil nil)
    ("migratewallet" nil nil)
    ("mockscheduler" t)
    ("ping")
    ("preciousblock" t)
    ("prioritisetransaction" t nil t)
    ("pruneblockchain" t)
    ("psbtbumpfee" t nil)
    ("reconsiderblock" t)
    ("removeprunedfunds" t)
    ("rescanblockchain" nil nil)
    ("restorewallet" t t nil)
    ("savemempool")
    ("scanblocks" t nil nil nil nil nil)
    ("scantxoutset" t nil)
    ("send" t nil nil nil nil nil)
    ("sendall" t nil nil nil nil)
    ("sendmany" nil t nil nil nil nil nil nil nil nil)
    ("sendmsgtopeer" t t t)
    ("sendrawtransaction" t nil nil)
    ("sendtoaddress" t t nil nil nil nil nil nil nil nil nil)
    ("setban" t t nil nil)
    ("setlabel" t t)
    ("setmocktime" t)
    ("setnetworkactive" t)
    ("setwalletflag" t nil)
    ("signmessage" t t)
    ("signmessagewithprivkey" t t)
    ("signrawtransactionwithkey" t t nil nil)
    ("signrawtransactionwithwallet" t nil nil)
    ("simulaterawtransaction" nil nil)
    ("stop" nil)
    ("submitblock" t nil)
    ("submitheader" t)
    ("submitpackage" t nil nil)
    ("syncwithvalidationinterfacequeue")
    ("testmempoolaccept" t nil)
    ("unloadwallet" nil nil)
    ("uptime")
    ("utxoupdatepsbt" t nil)
    ("validateaddress" t)
    ("verifychain" nil nil)
    ("verifymessage" t t t)
    ("verifytxoutproof" t)
    ("waitforblock" t nil)
    ("waitforblockheight" t nil)
    ("waitfornewblock" nil nil)
    ("walletcreatefundedpsbt" nil t nil nil nil nil)
    ("walletdisplayaddress" t)
    ("walletlock")
    ("walletpassphrase" t t)
    ("walletpassphrasechange" t t)
    ("walletprocesspsbt" t nil nil nil nil)
    ))

;;; --- The "hidden" category (Core's RegisterRPCCommands tables) ---
;;;
;;; Core's command table pairs every method with a CATEGORY, and one of them
;;; is literally "hidden": CRPCTable::help skips such a method when listing
;;; ALL commands (`if ((strCommand != "" || pcmd->category == "hidden") &&
;;; strMethod != strCommand) continue;', rpc/server.cpp:310-311) while
;;; `help <name>' still answers for it. These are the test and debugging
;;; entry points -- generate*, invalidateblock, setmocktime, echo,
;;; addconnection, getorphantxs -- which the framework calls by name and
;;; which Core deliberately keeps out of a user's command list.
;;;
;;; GENERATED from the {"hidden", &name} rows of Core's RegisterRPCCommands
;;; tables. Do not hand-edit.
(setf *rpc-hidden-methods*
  '("addconnection" "addpeeraddress" "echo" "echoipc" "echojson"
    "estimaterawfee" "generate" "generateblock" "generatetoaddress"
    "generatetodescriptor" "getmempoolfeeratediagram" "getorphantxs"
    "getrawaddrman" "invalidateblock" "mockscheduler" "reconsiderblock"
    "sendmsgtopeer" "setmocktime" "syncwithvalidationinterfacequeue"))

;;; --- Each method's arguments as Core's one-line help renders them ---
;;;
;;; RPCHelpMan::ToString's summary line renders every argument with
;;; RPCArg::ToString(oneline=true) (rpc/util.cpp:1249-1291): a string argument
;;; is quoted, a number or bool is its bare name, and an ARR or OBJ argument is
;;; its INNER arguments -- `[{"txid":"hex","vout":n,"sequence":n},...]',
;;; `{"rollback":n,...}' -- unless its declaration overrides that with an
;;; oneline_description ("[scanobjects,...]", "stats", "options"). The name and
;;; type tables above carry TOP-LEVEL arguments only, so they cannot express a
;;; structured one; this row is that rendering, one string per argument, in
;;; declaration order. A row STOPS at Core's first hidden argument, as
;;; RPCHelpMan::ToString does (`if (arg.m_opts.hidden) break', :778) -- which
;;; is why `stop', whose only argument is hidden, has no cells.
;;;
;;; GENERATED by scripts/gen-rpc-arg-names.py --oneline. Do not hand-edit:
;;; rerun the script against refs/bitcoin.

(setf *rpc-arg-oneline*
  '(
    ("abandontransaction" "\"txid\"")
    ("abortprivatebroadcast" "\"id\"")
    ("abortrescan")
    ("addconnection" "\"address\"" "\"connection_type\"" "v2transport")
    ("addnode" "\"node\"" "\"command\"" "v2transport")
    ("addpeeraddress" "\"address\"" "port" "tried")
    ("analyzepsbt" "\"psbt\"")
    ("backupwallet" "\"destination\"")
    ("bumpfee" "\"txid\"" "options")
    ("bumpfee_helper" "\"txid\"" "options")
    ("clearbanned")
    ("combinepsbt" "[\"psbt\",...]")
    ("combinerawtransaction" "[\"hexstring\",...]")
    ("converttopsbt" "\"hexstring\"" "permitsigdata" "iswitness")
    ("createmultisig" "nrequired" "[\"key\",...]" "\"address_type\"")
    ("createpsbt" "[{\"txid\":\"hex\",\"vout\":n,\"sequence\":n},...]" "[{\"address\":amount,...},{\"data\":\"hex\"},...]" "locktime" "replaceable" "version")
    ("createrawtransaction" "[{\"txid\":\"hex\",\"vout\":n,\"sequence\":n},...]" "[{\"address\":amount,...},{\"data\":\"hex\"},...]" "locktime" "replaceable" "version")
    ("createwallet" "\"wallet_name\"" "disable_private_keys" "blank" "\"passphrase\"" "avoid_reuse" "descriptors" "load_on_startup" "external_signer")
    ("createwalletdescriptor" "\"type\"" "{\"internal\":bool,\"hdkey\":\"str\",...}")
    ("decodepsbt" "\"psbt\"")
    ("decoderawtransaction" "\"hexstring\"" "iswitness")
    ("decodescript" "\"hexstring\"")
    ("deriveaddresses" "\"descriptor\"" "range")
    ("descriptorprocesspsbt" "\"psbt\"" "[\"\",{\"desc\":\"str\",\"range\":n or [n,n]},...]" "\"sighashtype\"" "bip32derivs" "finalize")
    ("disconnectnode" "\"address\"" "nodeid")
    ("dumptxoutset" "\"path\"" "\"type\"" "{\"rollback\":n,...}")
    ("echo" "\"arg0\"" "\"arg1\"" "\"arg2\"" "\"arg3\"" "\"arg4\"" "\"arg5\"" "\"arg6\"" "\"arg7\"" "\"arg8\"" "\"arg9\"")
    ("echoipc" "\"arg\"")
    ("echojson" "\"arg0\"" "\"arg1\"" "\"arg2\"" "\"arg3\"" "\"arg4\"" "\"arg5\"" "\"arg6\"" "\"arg7\"" "\"arg8\"" "\"arg9\"")
    ("encryptwallet" "\"passphrase\"")
    ("enumeratesigners")
    ("estimaterawfee" "conf_target" "threshold")
    ("estimatesmartfee" "conf_target" "\"estimate_mode\"")
    ("finalizepsbt" "\"psbt\"" "extract")
    ("fundrawtransaction" "\"hexstring\"" "options" "iswitness")
    ("generate")
    ("generateblock" "\"output\"" "[\"rawtx/txid\",...]" "submit")
    ("generatetoaddress" "nblocks" "\"address\"" "maxtries")
    ("generatetodescriptor" "num_blocks" "\"descriptor\"" "maxtries")
    ("getaddednodeinfo" "\"node\"")
    ("getaddressesbylabel" "\"label\"")
    ("getaddressinfo" "\"address\"")
    ("getaddrmaninfo")
    ("getbalance" "\"dummy\"" "minconf" "include_watchonly" "avoid_reuse")
    ("getbalances")
    ("getbestblockhash")
    ("getblock" "\"blockhash\"" "verbosity")
    ("getblockchaininfo")
    ("getblockcount")
    ("getblockfilter" "\"blockhash\"" "\"filtertype\"")
    ("getblockfrompeer" "\"blockhash\"" "peer_id")
    ("getblockhash" "height")
    ("getblockheader" "\"blockhash\"" "verbose")
    ("getblockstats" "hash_or_height" "stats")
    ("getblocktemplate" "{\"mode\":\"str\",\"capabilities\":[\"str\",...],\"rules\":[\"segwit\",\"str\",...],\"longpollid\":\"str\",\"data\":\"hex\"}")
    ("getchainstates")
    ("getchaintips")
    ("getchaintxstats" "nblocks" "\"blockhash\"")
    ("getconnectioncount")
    ("getdeploymentinfo" "\"blockhash\"")
    ("getdescriptoractivity" "[\"blockhash\",...]" "[scanobjects,...]" "include_mempool")
    ("getdescriptorinfo" "\"descriptor\"")
    ("getdifficulty")
    ("gethdkeys" "{\"active_only\":bool,\"private\":bool,...}")
    ("getindexinfo" "\"index_name\"")
    ("getmemoryinfo" "\"mode\"")
    ("getmempoolancestors" "\"txid\"" "verbose")
    ("getmempoolcluster" "\"txid\"")
    ("getmempooldescendants" "\"txid\"" "verbose")
    ("getmempoolentry" "\"txid\"")
    ("getmempoolfeeratediagram")
    ("getmempoolinfo")
    ("getmininginfo")
    ("getnettotals")
    ("getnetworkhashps" "nblocks" "height")
    ("getnetworkinfo")
    ("getnewaddress" "\"label\"" "\"address_type\"")
    ("getnodeaddresses" "count" "\"network\"")
    ("getorphantxs" "verbosity")
    ("getpeerinfo")
    ("getprioritisedtransactions")
    ("getprivatebroadcastinfo")
    ("getrawaddrman")
    ("getrawchangeaddress" "\"address_type\"")
    ("getrawmempool" "verbose" "mempool_sequence")
    ("getrawtransaction" "\"txid\"" "verbosity" "\"blockhash\"")
    ("getreceivedbyaddress" "\"address\"" "minconf" "include_immature_coinbase")
    ("getreceivedbylabel" "\"label\"" "minconf" "include_immature_coinbase")
    ("getrpcinfo")
    ("gettransaction" "\"txid\"" "include_watchonly" "verbose")
    ("gettxout" "\"txid\"" "n" "include_mempool")
    ("gettxoutproof" "[\"txid\",...]" "\"blockhash\"")
    ("gettxoutsetinfo" "\"hash_type\"" "hash_or_height" "use_index")
    ("gettxspendingprevout" "[{\"txid\":\"hex\",\"vout\":n},...]" "{\"mempool_only\":bool,\"return_spending_tx\":bool,...}")
    ("getwalletinfo")
    ("getzmqnotifications")
    ("help" "\"command\"")
    ("importdescriptors" "requests")
    ("importmempool" "\"filepath\"" "options")
    ("importprunedfunds" "\"rawtransaction\"" "\"txoutproof\"")
    ("invalidateblock" "\"blockhash\"")
    ("joinpsbts" "[\"psbt\",...]")
    ("keypoolrefill" "newsize")
    ("listaddressgroupings")
    ("listbanned")
    ("listdescriptors" "private")
    ("listlabels" "\"purpose\"")
    ("listlockunspent")
    ("listreceivedbyaddress" "minconf" "include_empty" "include_watchonly" "\"address_filter\"" "include_immature_coinbase")
    ("listreceivedbylabel" "minconf" "include_empty" "include_watchonly" "include_immature_coinbase")
    ("listsinceblock" "\"blockhash\"" "target_confirmations" "include_watchonly" "include_removed" "include_change" "\"label\"")
    ("listtransactions" "\"label\"" "count" "skip" "include_watchonly")
    ("listunspent" "minconf" "maxconf" "[\"address\",...]" "include_unsafe" "query_options")
    ("listwalletdir")
    ("listwallets")
    ("loadtxoutset" "\"path\"")
    ("loadwallet" "\"filename\"" "load_on_startup")
    ("lockunspent" "unlock" "[{\"txid\":\"hex\",\"vout\":n},...]" "persistent")
    ("logging" "[\"include_category\",...]" "[\"exclude_category\",...]")
    ("migratewallet" "\"wallet_name\"" "\"passphrase\"")
    ("mockscheduler" "delta_time")
    ("ping")
    ("preciousblock" "\"blockhash\"")
    ("prioritisetransaction" "\"txid\"" "dummy" "fee_delta")
    ("pruneblockchain" "height")
    ("psbtbumpfee" "\"txid\"" "options")
    ("reconsiderblock" "\"blockhash\"")
    ("removeprunedfunds" "\"txid\"")
    ("rescanblockchain" "start_height" "stop_height")
    ("restorewallet" "\"wallet_name\"" "\"backup_file\"" "load_on_startup")
    ("savemempool")
    ("scanblocks" "\"action\"" "[scanobjects,...]" "start_height" "stop_height" "\"filtertype\"" "options")
    ("scantxoutset" "\"action\"" "[scanobjects,...]")
    ("send" "[...]" "conf_target" "\"estimate_mode\"" "fee_rate" "options" "version")
    ("sendall" "[\"address\",{\"address\":amount,...},...]" "conf_target" "\"estimate_mode\"" "fee_rate" "options")
    ("sendmany" "\"\"" "{\"address\":amount,...}" "minconf" "\"comment\"" "[\"address\",...]" "replaceable" "conf_target" "\"estimate_mode\"" "fee_rate" "verbose")
    ("sendmsgtopeer" "peer_id" "\"msg_type\"" "\"msg\"")
    ("sendrawtransaction" "\"hexstring\"" "maxfeerate" "maxburnamount")
    ("sendtoaddress" "\"address\"" "amount" "\"comment\"" "\"comment_to\"" "subtractfeefromamount" "replaceable" "conf_target" "\"estimate_mode\"" "avoid_reuse" "fee_rate" "verbose")
    ("setban" "\"subnet\"" "\"command\"" "bantime" "absolute")
    ("setlabel" "\"address\"" "\"label\"")
    ("setmocktime" "timestamp")
    ("setnetworkactive" "state")
    ("setwalletflag" "\"flag\"" "value")
    ("signmessage" "\"address\"" "\"message\"")
    ("signmessagewithprivkey" "\"privkey\"" "\"message\"")
    ("signrawtransactionwithkey" "\"hexstring\"" "[\"privatekey\",...]" "[{\"txid\":\"hex\",\"vout\":n,\"scriptPubKey\":\"hex\",\"redeemScript\":\"hex\",\"witnessScript\":\"hex\",\"amount\":amount},...]" "\"sighashtype\"")
    ("signrawtransactionwithwallet" "\"hexstring\"" "[{\"txid\":\"hex\",\"vout\":n,\"scriptPubKey\":\"hex\",\"redeemScript\":\"hex\",\"witnessScript\":\"hex\",\"amount\":amount},...]" "\"sighashtype\"")
    ("simulaterawtransaction" "[\"rawtx\",...]" "{\"include_watchonly\":bool,...}")
    ("stop")
    ("submitblock" "\"hexdata\"" "\"dummy\"")
    ("submitheader" "\"hexdata\"")
    ("submitpackage" "[\"rawtx\",...]" "maxfeerate" "maxburnamount")
    ("syncwithvalidationinterfacequeue")
    ("testmempoolaccept" "[\"rawtx\",...]" "maxfeerate")
    ("unloadwallet" "\"wallet_name\"" "load_on_startup")
    ("uptime")
    ("utxoupdatepsbt" "\"psbt\"" "[\"\",{\"desc\":\"str\",\"range\":n or [n,n]},...]")
    ("validateaddress" "\"address\"")
    ("verifychain" "checklevel" "nblocks")
    ("verifymessage" "\"address\"" "\"signature\"" "\"message\"")
    ("verifytxoutproof" "\"proof\"")
    ("waitforblock" "\"blockhash\"" "timeout")
    ("waitforblockheight" "height" "timeout")
    ("waitfornewblock" "timeout" "\"current_tip\"")
    ("walletcreatefundedpsbt" "[{\"txid\":\"hex\",\"vout\":n,\"sequence\":n,\"weight\":n},...]" "[...]" "locktime" "options" "bip32derivs" "version")
    ("walletdisplayaddress" "\"address\"")
    ("walletlock")
    ("walletpassphrase" "\"passphrase\"" "timeout")
    ("walletpassphrasechange" "\"oldpassphrase\"" "\"newpassphrase\"")
    ("walletprocesspsbt" "\"psbt\"" "sign" "\"sighashtype\"" "bip32derivs" "finalize")
    ))
