(in-package #:bitcoin-lisp.rpc)

;;;; Tables GENERATED from Bitcoin Core's sources -- do not hand-edit.
;;;
;;; Three tables the RPC server consults for every call, each derived from
;;; Core by a script and cross-checked against Core's client.cpp by
;;; rpc-tests: *RPC-ARG-CONVERSIONS* (which positional arguments are JSON,
;;; from client.cpp's vRPCConvertParams), *RPC-NAMED-ONLY-ARGS* (members of
;;; an OBJ_NAMED_PARAMS options object) and *RPC-NAMED-ARG-NAMES* (every
;;; method's positional argument names, from the RPCHelpMan declarations;
;;; scripts/gen-rpc-arg-names.py). They are data: a Core upgrade means
;;; rerunning the scripts against refs/bitcoin, not editing rows. Kept apart
;;; from the handlers on purpose (refactoring plan, P2d-2 cancelled).

(defparameter *rpc-arg-conversions*
  '(
    ("addconnection" (2 "v2transport" . nil))
    ("addnode" (2 "v2transport" . nil))
    ("addpeeraddress" (1 "port" . nil) (2 "tried" . nil))
    ("analyzepsbt" (0 "psbt" . t))
    ("backupwallet" (0 "destination" . t))
    ("bumpfee" (1 "conf_target" . nil) (1 "fee_rate" . nil) (1 "options" . nil) (1 "original_change_index" . nil) (1 "outputs" . nil) (1 "replaceable" . nil))
    ("combinepsbt" (0 "txs" . nil))
    ("combinerawtransaction" (0 "txs" . nil))
    ("converttopsbt" (1 "permitsigdata" . nil) (2 "iswitness" . nil))
    ("createmultisig" (0 "nrequired" . nil) (1 "keys" . nil))
    ("createpsbt" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "replaceable" . nil) (4 "version" . nil))
    ("createrawtransaction" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "replaceable" . nil) (4 "version" . nil))
    ("createwallet" (0 "wallet_name" . t) (1 "disable_private_keys" . nil) (2 "blank" . nil) (3 "passphrase" . t) (4 "avoid_reuse" . nil) (5 "descriptors" . nil) (6 "load_on_startup" . nil) (7 "external_signer" . nil))
    ("createwalletdescriptor" (1 "internal" . nil) (1 "options" . nil))
    ("decodepsbt" (0 "psbt" . t))
    ("decoderawtransaction" (1 "iswitness" . nil))
    ("deriveaddresses" (1 "range" . nil))
    ("descriptorprocesspsbt" (0 "psbt" . t) (1 "descriptors" . nil) (2 "sighashtype" . t) (3 "bip32derivs" . nil) (4 "finalize" . nil))
    ("disconnectnode" (1 "nodeid" . nil))
    ("dumptxoutset" (0 "path" . t) (1 "type" . t) (2 "options" . nil) (2 "rollback" . nil))
    ("echojson" (0 "arg0" . nil) (1 "arg1" . nil) (2 "arg2" . nil) (3 "arg3" . nil) (4 "arg4" . nil) (5 "arg5" . nil) (6 "arg6" . nil) (7 "arg7" . nil) (8 "arg8" . nil) (9 "arg9" . nil))
    ("encryptwallet" (0 "passphrase" . t))
    ("estimaterawfee" (0 "conf_target" . nil) (1 "threshold" . nil))
    ("estimatesmartfee" (0 "conf_target" . nil))
    ("finalizepsbt" (0 "psbt" . t) (1 "extract" . nil))
    ("fundrawtransaction" (1 "add_inputs" . nil) (1 "changePosition" . nil) (1 "conf_target" . nil) (1 "feeRate" . nil) (1 "fee_rate" . nil) (1 "includeWatching" . nil) (1 "include_unsafe" . nil) (1 "input_weights" . nil) (1 "lockUnspents" . nil) (1 "max_tx_weight" . nil) (1 "maxconf" . nil) (1 "minconf" . nil) (1 "options" . nil) (1 "replaceable" . nil) (1 "solving_data" . nil) (1 "subtractFeeFromOutputs" . nil) (2 "iswitness" . nil))
    ("generateblock" (1 "transactions" . nil) (2 "submit" . nil))
    ("generatetoaddress" (0 "nblocks" . nil) (2 "maxtries" . nil))
    ("generatetodescriptor" (0 "num_blocks" . nil) (2 "maxtries" . nil))
    ("getaddressesbylabel" (0 "label" . t))
    ("getbalance" (1 "minconf" . nil) (2 "include_watchonly" . nil) (3 "avoid_reuse" . nil))
    ("getblock" (1 "verbose" . nil) (1 "verbosity" . nil))
    ("getblockfrompeer" (1 "peer_id" . nil))
    ("getblockhash" (0 "height" . nil))
    ("getblockheader" (1 "verbose" . nil))
    ("getblockstats" (0 "hash_or_height" . nil) (1 "stats" . nil))
    ("getblocktemplate" (0 "template_request" . nil))
    ("getchaintxstats" (0 "nblocks" . nil))
    ("getdescriptoractivity" (0 "blockhashes" . nil) (1 "scanobjects" . nil) (2 "include_mempool" . nil))
    ("gethdkeys" (0 "active_only" . nil) (0 "options" . nil) (0 "private" . nil))
    ("getmempoolancestors" (1 "verbose" . nil))
    ("getmempooldescendants" (1 "verbose" . nil))
    ("getnetworkhashps" (0 "nblocks" . nil) (1 "height" . nil))
    ("getnewaddress" (0 "label" . t) (1 "address_type" . t))
    ("getnodeaddresses" (0 "count" . nil))
    ("getorphantxs" (0 "verbosity" . nil))
    ("getrawmempool" (0 "verbose" . nil) (1 "mempool_sequence" . nil))
    ("getrawtransaction" (1 "verbose" . nil) (1 "verbosity" . nil))
    ("getreceivedbyaddress" (1 "minconf" . nil) (2 "include_immature_coinbase" . nil))
    ("getreceivedbylabel" (0 "label" . t) (1 "minconf" . nil) (2 "include_immature_coinbase" . nil))
    ("gettransaction" (1 "include_watchonly" . nil) (2 "verbose" . nil))
    ("gettxout" (1 "n" . nil) (2 "include_mempool" . nil))
    ("gettxoutproof" (0 "txids" . nil))
    ("gettxoutsetinfo" (1 "hash_or_height" . nil) (2 "use_index" . nil))
    ("gettxspendingprevout" (0 "outputs" . nil) (1 "mempool_only" . nil) (1 "options" . nil) (1 "return_spending_tx" . nil))
    ("importdescriptors" (0 "requests" . nil))
    ("importmempool" (0 "filepath" . t) (1 "apply_fee_delta_priority" . nil) (1 "apply_unbroadcast_set" . nil) (1 "options" . nil) (1 "use_current_time" . nil))
    ("joinpsbts" (0 "txs" . nil))
    ("keypoolrefill" (0 "newsize" . nil))
    ("listdescriptors" (0 "private" . nil))
    ("listreceivedbyaddress" (0 "minconf" . nil) (1 "include_empty" . nil) (2 "include_watchonly" . nil) (4 "include_immature_coinbase" . nil))
    ("listreceivedbylabel" (0 "minconf" . nil) (1 "include_empty" . nil) (2 "include_watchonly" . nil) (3 "include_immature_coinbase" . nil))
    ("listsinceblock" (0 "blockhash" . t) (1 "target_confirmations" . nil) (2 "include_watchonly" . nil) (3 "include_removed" . nil) (4 "include_change" . nil) (5 "label" . t))
    ("listtransactions" (0 "label" . t) (1 "count" . nil) (2 "skip" . nil) (3 "include_watchonly" . nil))
    ("listunspent" (0 "minconf" . nil) (1 "maxconf" . nil) (2 "addresses" . nil) (3 "include_unsafe" . nil) (4 "include_immature_coinbase" . nil) (4 "maximumAmount" . nil) (4 "maximumCount" . nil) (4 "minimumAmount" . nil) (4 "minimumSumAmount" . nil) (4 "query_options" . nil))
    ("loadtxoutset" (0 "path" . t))
    ("loadwallet" (0 "filename" . t) (1 "load_on_startup" . nil))
    ("lockunspent" (0 "unlock" . nil) (1 "transactions" . nil) (2 "persistent" . nil))
    ("logging" (0 "include" . nil) (1 "exclude" . nil))
    ("prioritisetransaction" (1 "dummy" . nil) (2 "fee_delta" . nil))
    ("pruneblockchain" (0 "height" . nil))
    ("psbtbumpfee" (1 "conf_target" . nil) (1 "fee_rate" . nil) (1 "options" . nil) (1 "original_change_index" . nil) (1 "outputs" . nil) (1 "replaceable" . nil))
    ("rescanblockchain" (0 "start_height" . nil) (1 "stop_height" . nil))
    ("restorewallet" (0 "wallet_name" . t) (1 "backup_file" . t) (2 "load_on_startup" . nil))
    ("scanblocks" (1 "scanobjects" . nil) (2 "start_height" . nil) (3 "stop_height" . nil) (5 "filter_false_positives" . nil) (5 "options" . nil))
    ("scantxoutset" (1 "scanobjects" . nil))
    ("send" (0 "outputs" . nil) (1 "conf_target" . nil) (3 "fee_rate" . nil) (4 "add_inputs" . nil) (4 "add_to_wallet" . nil) (4 "change_position" . nil) (4 "conf_target" . nil) (4 "fee_rate" . nil) (4 "include_unsafe" . nil) (4 "include_watching" . nil) (4 "inputs" . nil) (4 "lock_unspents" . nil) (4 "locktime" . nil) (4 "max_tx_weight" . nil) (4 "maxconf" . nil) (4 "minconf" . nil) (4 "options" . nil) (4 "psbt" . nil) (4 "replaceable" . nil) (4 "solving_data" . nil) (4 "subtract_fee_from_outputs" . nil) (5 "version" . nil))
    ("sendall" (0 "recipients" . nil) (1 "conf_target" . nil) (3 "fee_rate" . nil) (4 "add_to_wallet" . nil) (4 "conf_target" . nil) (4 "fee_rate" . nil) (4 "include_watching" . nil) (4 "inputs" . nil) (4 "lock_unspents" . nil) (4 "locktime" . nil) (4 "maxconf" . nil) (4 "minconf" . nil) (4 "options" . nil) (4 "psbt" . nil) (4 "replaceable" . nil) (4 "send_max" . nil) (4 "solving_data" . nil) (4 "version" . nil))
    ("sendmany" (0 "dummy" . t) (1 "amounts" . nil) (2 "minconf" . nil) (3 "comment" . t) (4 "subtractfeefrom" . nil) (5 "replaceable" . nil) (6 "conf_target" . nil) (7 "estimate_mode" . t) (8 "fee_rate" . nil) (9 "verbose" . nil))
    ("sendmsgtopeer" (0 "peer_id" . nil))
    ("sendrawtransaction" (1 "maxfeerate" . nil) (2 "maxburnamount" . nil))
    ("sendtoaddress" (0 "address" . t) (1 "amount" . nil) (2 "comment" . t) (3 "comment_to" . t) (4 "subtractfeefromamount" . nil) (5 "replaceable" . nil) (6 "conf_target" . nil) (7 "estimate_mode" . t) (8 "avoid_reuse" . nil) (9 "fee_rate" . nil) (10 "verbose" . nil))
    ("setban" (2 "bantime" . nil) (3 "absolute" . nil))
    ("setlabel" (1 "label" . t))
    ("mockscheduler" (0 "delta_time" . nil))
    ("setmocktime" (0 "timestamp" . nil))
    ("setnetworkactive" (0 "state" . nil))
    ("setwalletflag" (1 "value" . nil))
    ("signmessage" (1 "message" . t))
    ("signmessagewithprivkey" (1 "message" . t))
    ("signrawtransactionwithkey" (1 "privkeys" . nil) (2 "prevtxs" . nil))
    ("signrawtransactionwithwallet" (1 "prevtxs" . nil))
    ("simulaterawtransaction" (0 "rawtxs" . nil) (1 "include_watchonly" . nil) (1 "options" . nil))
    ("stop" (0 "wait" . nil))
    ("submitpackage" (0 "package" . nil) (1 "maxfeerate" . nil) (2 "maxburnamount" . nil))
    ("testmempoolaccept" (0 "rawtxs" . nil) (1 "maxfeerate" . nil))
    ("unloadwallet" (0 "wallet_name" . t) (1 "load_on_startup" . nil))
    ("utxoupdatepsbt" (0 "psbt" . t) (1 "descriptors" . nil))
    ("verifychain" (0 "checklevel" . nil) (1 "nblocks" . nil))
    ("verifymessage" (1 "signature" . t) (2 "message" . t))
    ("waitforblock" (1 "timeout" . nil))
    ("waitforblockheight" (0 "height" . nil) (1 "timeout" . nil))
    ("waitfornewblock" (0 "timeout" . nil))
    ("walletcreatefundedpsbt" (0 "inputs" . nil) (1 "outputs" . nil) (2 "locktime" . nil) (3 "add_inputs" . nil) (3 "changePosition" . nil) (3 "conf_target" . nil) (3 "feeRate" . nil) (3 "fee_rate" . nil) (3 "includeWatching" . nil) (3 "include_unsafe" . nil) (3 "lockUnspents" . nil) (3 "max_tx_weight" . nil) (3 "maxconf" . nil) (3 "minconf" . nil) (3 "options" . nil) (3 "replaceable" . nil) (3 "solving_data" . nil) (3 "subtractFeeFromOutputs" . nil) (4 "bip32derivs" . nil) (5 "version" . nil))
    ("walletpassphrase" (0 "passphrase" . t) (1 "timeout" . nil))
    ("walletpassphrasechange" (0 "oldpassphrase" . t) (1 "newpassphrase" . t))
    ("walletprocesspsbt" (0 "psbt" . t) (1 "sign" . nil) (2 "sighashtype" . t) (3 "bip32derivs" . nil) (4 "finalize" . nil)))
  "Per method, the (POSITION NAME . STRING-P) of every argument Core classifies
in src/rpc/client.cpp's vRPCConvertParams.

STRING-P is Core's `type == STR || type == STR_HEX` (RPCHelpMan::GetArgMap,
rpc/util.cpp:837-844) — TRUE means the argument is passed through as a string,
FALSE means a JSON-RPC client must parse it before sending. That distinction is
the whole content of the table, and it is what `bitcoin-cli` gets wrong if the
two implementations disagree.

GENERATED from Core's own client.cpp, restricted to the methods this node
implements, and kept honest by RPC-ARG-CONVERSIONS-MATCH-CORE, which re-parses
that file and compares. Editing an entry here by hand without changing Core is
how the two drift apart, so the test exists to make that impossible to do
quietly.")

;;; Members of an RPC's OBJ_NAMED_PARAMS options object, which Core lets a
;;; client pass as TOP-LEVEL named arguments.
;;;
;;; RPCHelpMan::GetArgNames emits these with named_only=true (rpc/util.cpp:750) and
;;; transformNamedArguments collects them into a fresh options object which it
;;; pushes at the options slot (rpc/server.cpp:408-415). Without them the server
;;; answers "Unknown named parameter fee_rate" to a call every Core client can
;;; make.
;;;
;;; ⚠️ Covers BOTH declaration forms. Matching only `RPCHelpMan{"name"` misses
;;; every RPC declared through a helper that takes the name as a PARAMETER —
;;; bumpfee and psbtbumpfee are declared that way (wallet/rpc/spend.cpp:960,
;;; 1166-1167), so both were absent and wallet_bumpfee.py died on fee_rate.
;;;
;;; GENERATED from Core's RPCHelpMan declarations. Do not hand-edit.
(setf *rpc-named-only-args*
  '(
    ("bumpfee" "conf_target" "fee_rate" "replaceable" "estimate_mode" "outputs" "original_change_index")
    ("createwalletdescriptor" "internal" "hdkey")
    ("dumptxoutset" "rollback")
    ("fundrawtransaction" "add_inputs" "include_unsafe" "minconf" "maxconf" "change_type" "fee_rate" "vout_index" "input_weights" "txid" "vout" "weight" "max_tx_weight")
    ("gethdkeys" "active_only" "private")
    ("gettxspendingprevout" "mempool_only" "return_spending_tx")
    ("importmempool" "use_current_time" "apply_fee_delta_priority" "apply_unbroadcast_set")
    ("listunspent" "include_immature_coinbase")
    ("psbtbumpfee" "conf_target" "fee_rate" "replaceable" "estimate_mode" "outputs" "original_change_index")
    ("scanblocks" "filter_false_positives")
    ("send" "add_inputs" "include_unsafe" "minconf" "maxconf" "add_to_wallet" "change_address" "change_position" "change_type" "fee_rate" "include_watching" "inputs" "txid" "vout" "sequence" "weight" "locktime" "lock_unspents" "psbt" "subtract_fee_from_outputs" "vout_index" "max_tx_weight")
    ("sendall" "add_to_wallet" "fee_rate" "include_watching" "inputs" "txid" "vout" "sequence" "locktime" "lock_unspents" "psbt" "send_max" "minconf" "maxconf" "version")
    ("simulaterawtransaction" "include_watchonly")
    ("walletcreatefundedpsbt" "add_inputs" "include_unsafe" "minconf" "maxconf" "change_type" "fee_rate" "vout_index" "max_tx_weight")))

;;; Positional argument names for every RPC method Core declares, in declaration
;;; order — what transformNamedArguments (rpc/server.cpp:396) matches an incoming
;;; named parameter against. A name containing #\\| lists aliases for one slot,
;;; exactly as Core stores it; getblock's "verbosity|verbose" is the case that
;;; matters, since older clients send the second spelling.
;;;
;;; GENERATED from Core's RPCHelpMan declarations by scripts/gen-rpc-arg-names.py,
;;; which walks src/rpc/*.cpp and src/wallet/rpc/*.cpp. Do not hand-edit: rerun the
;;; script against refs/bitcoin.
;;;
;;; It has to come from RPCHelpMan and not from client.cpp, which is where the earlier
;;; type-conversion table comes from. client.cpp lists only arguments that need
;;; JSON CONVERSION, so it structurally omits every STRING argument. A named-parameter
;;; table derived from it is missing `scantxoutset action`, `setban subnet`,
;;; `addnode command`, and about a hundred more — and, worse, the positions of the
;;; arguments that ARE listed are Core's real positions, so a table built from it
;;; disagrees with itself about where an argument sits.
;;;
;;; The hand-curated 43-method predecessor is why this exists. MiniWallet — which a
;;; large share of Core's functional suite instantiates — opens with
;;; `scantxoutset(action="start", ...)`, and `action` was not in the table, so
;;; the node answered "Unknown named parameter action" and the test died in
;;; setup. Found by running the suite, not by reading it.
(setf *rpc-named-arg-names*
  '(
    ("abandontransaction" "txid")
    ("abortprivatebroadcast" "id")
    ("abortrescan")
    ("addconnection" "address" "connection_type" "v2transport")
    ("addnode" "node" "command" "v2transport")
    ("addpeeraddress" "address" "port" "tried")
    ("analyzepsbt" "psbt")
    ("backupwallet" "destination")
    ("bumpfee" "txid" "options")
    ("clearbanned")
    ("combinepsbt" "txs")
    ("combinerawtransaction" "txs")
    ("converttopsbt" "hexstring" "permitsigdata" "iswitness")
    ("createmultisig" "nrequired" "keys" "address_type")
    ("createpsbt" "inputs" "outputs" "locktime" "replaceable" "version")
    ("createrawtransaction" "inputs" "outputs" "locktime" "replaceable" "version")
    ("createwallet" "wallet_name" "disable_private_keys" "blank" "passphrase" "avoid_reuse" "descriptors" "load_on_startup" "external_signer")
    ("createwalletdescriptor" "type" "options")
    ("decodepsbt" "psbt")
    ("decoderawtransaction" "hexstring" "iswitness")
    ("decodescript" "hexstring")
    ("deriveaddresses" "descriptor" "range")
    ("descriptorprocesspsbt" "psbt" "descriptors" "sighashtype" "bip32derivs" "finalize")
    ("disconnectnode" "address" "nodeid")
    ("dumptxoutset" "path" "type" "options")
    ("echo" "arg0" "arg1" "arg2" "arg3" "arg4" "arg5" "arg6" "arg7" "arg8" "arg9")
    ("echoipc" "arg")
    ("echojson" "arg0" "arg1" "arg2" "arg3" "arg4" "arg5" "arg6" "arg7" "arg8" "arg9")
    ("encryptwallet" "passphrase")
    ("enumeratesigners")
    ("estimaterawfee" "conf_target" "threshold")
    ("estimatesmartfee" "conf_target" "estimate_mode")
    ("finalizepsbt" "psbt" "extract")
    ("fundrawtransaction" "hexstring" "options" "iswitness")
    ("generate")
    ("generateblock" "output" "transactions" "submit")
    ("generatetoaddress" "nblocks" "address" "maxtries")
    ("generatetodescriptor" "num_blocks" "descriptor" "maxtries")
    ("getaddednodeinfo" "node")
    ("getaddressesbylabel" "label")
    ("getaddressinfo" "address")
    ("getaddrmaninfo")
    ("getbalance" "dummy" "minconf" "include_watchonly" "avoid_reuse")
    ("getbalances")
    ("getbestblockhash")
    ("getblock" "blockhash" "verbosity|verbose")
    ("getblockchaininfo")
    ("getblockcount")
    ("getblockfilter" "blockhash" "filtertype")
    ("getblockfrompeer" "blockhash" "peer_id")
    ("getblockhash" "height")
    ("getblockheader" "blockhash" "verbose")
    ("getblockstats" "hash_or_height" "stats")
    ("getblocktemplate" "template_request")
    ("getchainstates")
    ("getchaintips")
    ("getchaintxstats" "nblocks" "blockhash")
    ("getconnectioncount")
    ("getdeploymentinfo" "blockhash")
    ("getdescriptoractivity" "blockhashes" "scanobjects" "include_mempool")
    ("getdescriptorinfo" "descriptor")
    ("getdifficulty")
    ("gethdkeys" "options")
    ("getindexinfo" "index_name")
    ("getmemoryinfo" "mode")
    ("getmempoolancestors" "txid" "verbose")
    ("getmempoolcluster" "txid")
    ("getmempooldescendants" "txid" "verbose")
    ("getmempoolentry" "txid")
    ("getmempoolfeeratediagram")
    ("getmempoolinfo")
    ("getmininginfo")
    ("getnettotals")
    ("getnetworkhashps" "nblocks" "height")
    ("getnetworkinfo")
    ("getnewaddress" "label" "address_type")
    ("getnodeaddresses" "count" "network")
    ("getorphantxs" "verbosity")
    ("getpeerinfo")
    ("getprioritisedtransactions")
    ("getprivatebroadcastinfo")
    ("getrawaddrman")
    ("getrawchangeaddress" "address_type")
    ("getrawmempool" "verbose" "mempool_sequence")
    ("getrawtransaction" "txid" "verbosity|verbose" "blockhash")
    ("getreceivedbyaddress" "address" "minconf" "include_immature_coinbase")
    ("getreceivedbylabel" "label" "minconf" "include_immature_coinbase")
    ("getrpcinfo")
    ("gettransaction" "txid" "include_watchonly" "verbose")
    ("gettxout" "txid" "n" "include_mempool")
    ("gettxoutproof" "txids" "blockhash")
    ("gettxoutsetinfo" "hash_type" "hash_or_height" "use_index")
    ("gettxspendingprevout" "outputs" "options")
    ("getwalletinfo")
    ("getzmqnotifications")
    ("help" "command")
    ("importdescriptors" "requests")
    ("importmempool" "filepath" "options")
    ("importprunedfunds" "rawtransaction" "txoutproof")
    ("invalidateblock" "blockhash")
    ("joinpsbts" "txs")
    ("keypoolrefill" "newsize")
    ("listaddressgroupings")
    ("listbanned")
    ("listdescriptors" "private")
    ("listlabels" "purpose")
    ("listlockunspent")
    ("listreceivedbyaddress" "minconf" "include_empty" "include_watchonly" "address_filter" "include_immature_coinbase")
    ("listreceivedbylabel" "minconf" "include_empty" "include_watchonly" "include_immature_coinbase")
    ("listsinceblock" "blockhash" "target_confirmations" "include_watchonly" "include_removed" "include_change" "label")
    ("listtransactions" "label" "count" "skip" "include_watchonly")
    ("listunspent" "minconf" "maxconf" "addresses" "include_unsafe" "query_options")
    ("listwalletdir")
    ("listwallets")
    ("loadtxoutset" "path")
    ("loadwallet" "filename" "load_on_startup")
    ("lockunspent" "unlock" "transactions" "persistent")
    ("logging" "include" "exclude")
    ("migratewallet" "wallet_name" "passphrase")
    ("mockscheduler" "delta_time")
    ("ping")
    ("preciousblock" "blockhash")
    ("prioritisetransaction" "txid" "dummy" "fee_delta")
    ("pruneblockchain" "height")
    ("psbtbumpfee" "txid" "options")
    ("reconsiderblock" "blockhash")
    ("removeprunedfunds" "txid")
    ("rescanblockchain" "start_height" "stop_height")
    ("restorewallet" "wallet_name" "backup_file" "load_on_startup")
    ("savemempool")
    ("scanblocks" "action" "scanobjects" "start_height" "stop_height" "filtertype" "options")
    ("scantxoutset" "action" "scanobjects")
    ("send" "outputs" "conf_target" "estimate_mode" "fee_rate" "options" "version")
    ("sendall" "recipients" "conf_target" "estimate_mode" "fee_rate" "options")
    ("sendmany" "dummy" "amounts" "minconf" "comment" "subtractfeefrom" "replaceable" "conf_target" "estimate_mode" "fee_rate" "verbose")
    ("sendmsgtopeer" "peer_id" "msg_type" "msg")
    ("sendrawtransaction" "hexstring" "maxfeerate" "maxburnamount")
    ("sendtoaddress" "address" "amount" "comment" "comment_to" "subtractfeefromamount" "replaceable" "conf_target" "estimate_mode" "avoid_reuse" "fee_rate" "verbose")
    ("setban" "subnet" "command" "bantime" "absolute")
    ("setlabel" "address" "label")
    ("setmocktime" "timestamp")
    ("setnetworkactive" "state")
    ("setwalletflag" "flag" "value")
    ("signmessage" "address" "message")
    ("signmessagewithprivkey" "privkey" "message")
    ("signrawtransactionwithkey" "hexstring" "privkeys" "prevtxs" "sighashtype")
    ("signrawtransactionwithwallet" "hexstring" "prevtxs" "sighashtype")
    ("simulaterawtransaction" "rawtxs" "options")
    ("stop" "wait")
    ("submitblock" "hexdata" "dummy")
    ("submitheader" "hexdata")
    ("submitpackage" "package" "maxfeerate" "maxburnamount")
    ("syncwithvalidationinterfacequeue")
    ("testmempoolaccept" "rawtxs" "maxfeerate")
    ("unloadwallet" "wallet_name" "load_on_startup")
    ("uptime")
    ("utxoupdatepsbt" "psbt" "descriptors")
    ("validateaddress" "address")
    ("verifychain" "checklevel" "nblocks")
    ("verifymessage" "address" "signature" "message")
    ("verifytxoutproof" "proof")
    ("waitforblock" "blockhash" "timeout")
    ("waitforblockheight" "height" "timeout")
    ("waitfornewblock" "timeout" "current_tip")
    ("walletcreatefundedpsbt" "inputs" "outputs" "locktime" "options" "bip32derivs" "version")
    ("walletdisplayaddress" "address")
    ("walletlock")
    ("walletpassphrase" "passphrase" "timeout")
    ("walletpassphrasechange" "oldpassphrase" "newpassphrase")
    ("walletprocesspsbt" "psbt" "sign" "sighashtype" "bip32derivs" "finalize")
    ))
