(in-package #:bitcoin-lisp.cli)

;;;; Command-line arguments to JSON-RPC params (Core rpc/client.cpp)
;;;
;;; bitcoin-cli sends every argument as a JSON STRING unless the table below
;;; says the (method, position) or (method, name) is JSON. Nothing else
;;; decides it -- not the argument's shape, not the server's declared types --
;;; so `bitcoin-cli getblockhash 5' works only because the table lists
;;; getblockhash's height, and `bitcoin-cli echo 1' sends the string "1".
;;; The rows are Core's vRPCConvertParams at the project pin (d3056bc149,
;;; rpc/client.cpp:57-393), transcribed mechanically, in Core's order: the
;;; lookups are first-match, like Core's std::ranges::find_if. This is NOT the
;;; server's *RPC-ARG-CONVERSIONS* (src/rpc/core-tables.lisp), which comes from
;;; the RPCHelpMan declarations and cannot say JSON-or-string; Core keeps the
;;; two apart as well, and rpc_help.py compares them.

(defparameter *rpc-convert-params*
  '(
    ("setmocktime" 0 "timestamp" :json)
    ("mockscheduler" 0 "delta_time" :json)
    ("utxoupdatepsbt" 0 "psbt" :string)
    ("utxoupdatepsbt" 1 "descriptors" :json)
    ("generatetoaddress" 0 "nblocks" :json)
    ("generatetoaddress" 2 "maxtries" :json)
    ("generatetodescriptor" 0 "num_blocks" :json)
    ("generatetodescriptor" 2 "maxtries" :json)
    ("generateblock" 1 "transactions" :json)
    ("generateblock" 2 "submit" :json)
    ("getnetworkhashps" 0 "nblocks" :json)
    ("getnetworkhashps" 1 "height" :json)
    ("sendtoaddress" 0 "address" :string)
    ("sendtoaddress" 1 "amount" :json)
    ("sendtoaddress" 2 "comment" :string)
    ("sendtoaddress" 3 "comment_to" :string)
    ("sendtoaddress" 4 "subtractfeefromamount" :json)
    ("sendtoaddress" 5 "replaceable" :json)
    ("sendtoaddress" 6 "conf_target" :json)
    ("sendtoaddress" 7 "estimate_mode" :string)
    ("sendtoaddress" 8 "avoid_reuse" :json)
    ("sendtoaddress" 9 "fee_rate" :json)
    ("sendtoaddress" 10 "verbose" :json)
    ("getreceivedbyaddress" 1 "minconf" :json)
    ("getreceivedbyaddress" 2 "include_immature_coinbase" :json)
    ("getreceivedbylabel" 0 "label" :string)
    ("getreceivedbylabel" 1 "minconf" :json)
    ("getreceivedbylabel" 2 "include_immature_coinbase" :json)
    ("listreceivedbyaddress" 0 "minconf" :json)
    ("listreceivedbyaddress" 1 "include_empty" :json)
    ("listreceivedbyaddress" 2 "include_watchonly" :json)
    ("listreceivedbyaddress" 4 "include_immature_coinbase" :json)
    ("listreceivedbylabel" 0 "minconf" :json)
    ("listreceivedbylabel" 1 "include_empty" :json)
    ("listreceivedbylabel" 2 "include_watchonly" :json)
    ("listreceivedbylabel" 3 "include_immature_coinbase" :json)
    ("getbalance" 1 "minconf" :json)
    ("getbalance" 2 "include_watchonly" :json)
    ("getbalance" 3 "avoid_reuse" :json)
    ("getblockfrompeer" 1 "peer_id" :json)
    ("getblockhash" 0 "height" :json)
    ("waitforblockheight" 0 "height" :json)
    ("waitforblockheight" 1 "timeout" :json)
    ("waitforblock" 1 "timeout" :json)
    ("waitfornewblock" 0 "timeout" :json)
    ("listtransactions" 0 "label" :string)
    ("listtransactions" 1 "count" :json)
    ("listtransactions" 2 "skip" :json)
    ("listtransactions" 3 "include_watchonly" :json)
    ("walletpassphrase" 0 "passphrase" :string)
    ("walletpassphrase" 1 "timeout" :json)
    ("getblocktemplate" 0 "template_request" :json)
    ("listsinceblock" 0 "blockhash" :string)
    ("listsinceblock" 1 "target_confirmations" :json)
    ("listsinceblock" 2 "include_watchonly" :json)
    ("listsinceblock" 3 "include_removed" :json)
    ("listsinceblock" 4 "include_change" :json)
    ("listsinceblock" 5 "label" :string)
    ("sendmany" 0 "dummy" :string)
    ("sendmany" 1 "amounts" :json)
    ("sendmany" 2 "minconf" :json)
    ("sendmany" 3 "comment" :string)
    ("sendmany" 4 "subtractfeefrom" :json)
    ("sendmany" 5 "replaceable" :json)
    ("sendmany" 6 "conf_target" :json)
    ("sendmany" 7 "estimate_mode" :string)
    ("sendmany" 8 "fee_rate" :json)
    ("sendmany" 9 "verbose" :json)
    ("deriveaddresses" 1 "range" :json)
    ("scanblocks" 1 "scanobjects" :json)
    ("scanblocks" 2 "start_height" :json)
    ("scanblocks" 3 "stop_height" :json)
    ("scanblocks" 5 "options" :json)
    ("scanblocks" 5 "filter_false_positives" :json)
    ("getdescriptoractivity" 0 "blockhashes" :json)
    ("getdescriptoractivity" 1 "scanobjects" :json)
    ("getdescriptoractivity" 2 "include_mempool" :json)
    ("scantxoutset" 1 "scanobjects" :json)
    ("createmultisig" 0 "nrequired" :json)
    ("createmultisig" 1 "keys" :json)
    ("listunspent" 0 "minconf" :json)
    ("listunspent" 1 "maxconf" :json)
    ("listunspent" 2 "addresses" :json)
    ("listunspent" 3 "include_unsafe" :json)
    ("listunspent" 4 "query_options" :json)
    ("listunspent" 4 "minimumAmount" :json)
    ("listunspent" 4 "maximumAmount" :json)
    ("listunspent" 4 "maximumCount" :json)
    ("listunspent" 4 "minimumSumAmount" :json)
    ("listunspent" 4 "include_immature_coinbase" :json)
    ("getblock" 1 "verbosity" :json)
    ("getblock" 1 "verbose" :json)
    ("getblockheader" 1 "verbose" :json)
    ("getchaintxstats" 0 "nblocks" :json)
    ("gettransaction" 1 "include_watchonly" :json)
    ("gettransaction" 2 "verbose" :json)
    ("getrawtransaction" 1 "verbosity" :json)
    ("getrawtransaction" 1 "verbose" :json)
    ("createrawtransaction" 0 "inputs" :json)
    ("createrawtransaction" 1 "outputs" :json)
    ("createrawtransaction" 2 "locktime" :json)
    ("createrawtransaction" 3 "replaceable" :json)
    ("createrawtransaction" 4 "version" :json)
    ("decoderawtransaction" 1 "iswitness" :json)
    ("signrawtransactionwithkey" 1 "privkeys" :json)
    ("signrawtransactionwithkey" 2 "prevtxs" :json)
    ("signrawtransactionwithwallet" 1 "prevtxs" :json)
    ("sendrawtransaction" 1 "maxfeerate" :json)
    ("sendrawtransaction" 2 "maxburnamount" :json)
    ("testmempoolaccept" 0 "rawtxs" :json)
    ("testmempoolaccept" 1 "maxfeerate" :json)
    ("submitpackage" 0 "package" :json)
    ("submitpackage" 1 "maxfeerate" :json)
    ("submitpackage" 2 "maxburnamount" :json)
    ("combinerawtransaction" 0 "txs" :json)
    ("fundrawtransaction" 1 "options" :json)
    ("fundrawtransaction" 1 "add_inputs" :json)
    ("fundrawtransaction" 1 "include_unsafe" :json)
    ("fundrawtransaction" 1 "minconf" :json)
    ("fundrawtransaction" 1 "maxconf" :json)
    ("fundrawtransaction" 1 "changePosition" :json)
    ("fundrawtransaction" 1 "includeWatching" :json)
    ("fundrawtransaction" 1 "lockUnspents" :json)
    ("fundrawtransaction" 1 "fee_rate" :json)
    ("fundrawtransaction" 1 "feeRate" :json)
    ("fundrawtransaction" 1 "subtractFeeFromOutputs" :json)
    ("fundrawtransaction" 1 "input_weights" :json)
    ("fundrawtransaction" 1 "conf_target" :json)
    ("fundrawtransaction" 1 "replaceable" :json)
    ("fundrawtransaction" 1 "solving_data" :json)
    ("fundrawtransaction" 1 "max_tx_weight" :json)
    ("fundrawtransaction" 2 "iswitness" :json)
    ("walletcreatefundedpsbt" 0 "inputs" :json)
    ("walletcreatefundedpsbt" 1 "outputs" :json)
    ("walletcreatefundedpsbt" 2 "locktime" :json)
    ("walletcreatefundedpsbt" 3 "options" :json)
    ("walletcreatefundedpsbt" 3 "add_inputs" :json)
    ("walletcreatefundedpsbt" 3 "include_unsafe" :json)
    ("walletcreatefundedpsbt" 3 "minconf" :json)
    ("walletcreatefundedpsbt" 3 "maxconf" :json)
    ("walletcreatefundedpsbt" 3 "changePosition" :json)
    ("walletcreatefundedpsbt" 3 "includeWatching" :json)
    ("walletcreatefundedpsbt" 3 "lockUnspents" :json)
    ("walletcreatefundedpsbt" 3 "fee_rate" :json)
    ("walletcreatefundedpsbt" 3 "feeRate" :json)
    ("walletcreatefundedpsbt" 3 "subtractFeeFromOutputs" :json)
    ("walletcreatefundedpsbt" 3 "conf_target" :json)
    ("walletcreatefundedpsbt" 3 "replaceable" :json)
    ("walletcreatefundedpsbt" 3 "solving_data" :json)
    ("walletcreatefundedpsbt" 3 "max_tx_weight" :json)
    ("walletcreatefundedpsbt" 4 "bip32derivs" :json)
    ("walletcreatefundedpsbt" 5 "version" :json)
    ("walletprocesspsbt" 0 "psbt" :string)
    ("walletprocesspsbt" 1 "sign" :json)
    ("walletprocesspsbt" 2 "sighashtype" :string)
    ("walletprocesspsbt" 3 "bip32derivs" :json)
    ("walletprocesspsbt" 4 "finalize" :json)
    ("descriptorprocesspsbt" 0 "psbt" :string)
    ("descriptorprocesspsbt" 1 "descriptors" :json)
    ("descriptorprocesspsbt" 2 "sighashtype" :string)
    ("descriptorprocesspsbt" 3 "bip32derivs" :json)
    ("descriptorprocesspsbt" 4 "finalize" :json)
    ("createpsbt" 0 "inputs" :json)
    ("createpsbt" 1 "outputs" :json)
    ("createpsbt" 2 "locktime" :json)
    ("createpsbt" 3 "replaceable" :json)
    ("createpsbt" 4 "version" :json)
    ("combinepsbt" 0 "txs" :json)
    ("joinpsbts" 0 "txs" :json)
    ("finalizepsbt" 0 "psbt" :string)
    ("finalizepsbt" 1 "extract" :json)
    ("converttopsbt" 1 "permitsigdata" :json)
    ("converttopsbt" 2 "iswitness" :json)
    ("gettxout" 1 "n" :json)
    ("gettxout" 2 "include_mempool" :json)
    ("gettxoutproof" 0 "txids" :json)
    ("gettxoutsetinfo" 1 "hash_or_height" :json-or-string)
    ("gettxoutsetinfo" 2 "use_index" :json)
    ("dumptxoutset" 0 "path" :string)
    ("dumptxoutset" 1 "type" :string)
    ("dumptxoutset" 2 "options" :json)
    ("dumptxoutset" 2 "rollback" :json-or-string)
    ("lockunspent" 0 "unlock" :json)
    ("lockunspent" 1 "transactions" :json)
    ("lockunspent" 2 "persistent" :json)
    ("send" 0 "outputs" :json)
    ("send" 1 "conf_target" :json)
    ("send" 3 "fee_rate" :json)
    ("send" 4 "options" :json)
    ("send" 4 "add_inputs" :json)
    ("send" 4 "include_unsafe" :json)
    ("send" 4 "minconf" :json)
    ("send" 4 "maxconf" :json)
    ("send" 4 "add_to_wallet" :json)
    ("send" 4 "change_position" :json)
    ("send" 4 "fee_rate" :json)
    ("send" 4 "include_watching" :json)
    ("send" 4 "inputs" :json)
    ("send" 4 "locktime" :json)
    ("send" 4 "lock_unspents" :json)
    ("send" 4 "psbt" :json)
    ("send" 4 "subtract_fee_from_outputs" :json)
    ("send" 4 "conf_target" :json)
    ("send" 4 "replaceable" :json)
    ("send" 4 "solving_data" :json)
    ("send" 4 "max_tx_weight" :json)
    ("send" 5 "version" :json)
    ("sendall" 0 "recipients" :json)
    ("sendall" 1 "conf_target" :json)
    ("sendall" 3 "fee_rate" :json)
    ("sendall" 4 "options" :json)
    ("sendall" 4 "add_to_wallet" :json)
    ("sendall" 4 "fee_rate" :json)
    ("sendall" 4 "include_watching" :json)
    ("sendall" 4 "inputs" :json)
    ("sendall" 4 "locktime" :json)
    ("sendall" 4 "lock_unspents" :json)
    ("sendall" 4 "psbt" :json)
    ("sendall" 4 "send_max" :json)
    ("sendall" 4 "minconf" :json)
    ("sendall" 4 "maxconf" :json)
    ("sendall" 4 "conf_target" :json)
    ("sendall" 4 "replaceable" :json)
    ("sendall" 4 "solving_data" :json)
    ("sendall" 4 "version" :json)
    ("simulaterawtransaction" 0 "rawtxs" :json)
    ("simulaterawtransaction" 1 "options" :json)
    ("simulaterawtransaction" 1 "include_watchonly" :json)
    ("importmempool" 0 "filepath" :string)
    ("importmempool" 1 "options" :json)
    ("importmempool" 1 "apply_fee_delta_priority" :json)
    ("importmempool" 1 "use_current_time" :json)
    ("importmempool" 1 "apply_unbroadcast_set" :json)
    ("importdescriptors" 0 "requests" :json)
    ("listdescriptors" 0 "private" :json)
    ("verifychain" 0 "checklevel" :json)
    ("verifychain" 1 "nblocks" :json)
    ("getblockstats" 0 "hash_or_height" :json-or-string)
    ("getblockstats" 1 "stats" :json)
    ("pruneblockchain" 0 "height" :json)
    ("keypoolrefill" 0 "newsize" :json)
    ("getrawmempool" 0 "verbose" :json)
    ("getrawmempool" 1 "mempool_sequence" :json)
    ("getorphantxs" 0 "verbosity" :json)
    ("estimatesmartfee" 0 "conf_target" :json)
    ("estimaterawfee" 0 "conf_target" :json)
    ("estimaterawfee" 1 "threshold" :json)
    ("prioritisetransaction" 1 "dummy" :json)
    ("prioritisetransaction" 2 "fee_delta" :json)
    ("setban" 2 "bantime" :json)
    ("setban" 3 "absolute" :json)
    ("setnetworkactive" 0 "state" :json)
    ("setwalletflag" 1 "value" :json)
    ("getmempoolancestors" 1 "verbose" :json)
    ("getmempooldescendants" 1 "verbose" :json)
    ("gettxspendingprevout" 0 "outputs" :json)
    ("gettxspendingprevout" 1 "options" :json)
    ("gettxspendingprevout" 1 "mempool_only" :json)
    ("gettxspendingprevout" 1 "return_spending_tx" :json)
    ("bumpfee" 1 "options" :json)
    ("bumpfee" 1 "conf_target" :json)
    ("bumpfee" 1 "fee_rate" :json)
    ("bumpfee" 1 "replaceable" :json)
    ("bumpfee" 1 "outputs" :json)
    ("bumpfee" 1 "original_change_index" :json)
    ("psbtbumpfee" 1 "options" :json)
    ("psbtbumpfee" 1 "conf_target" :json)
    ("psbtbumpfee" 1 "fee_rate" :json)
    ("psbtbumpfee" 1 "replaceable" :json)
    ("psbtbumpfee" 1 "outputs" :json)
    ("psbtbumpfee" 1 "original_change_index" :json)
    ("logging" 0 "include" :json)
    ("logging" 1 "exclude" :json)
    ("disconnectnode" 1 "nodeid" :json)
    ("gethdkeys" 0 "active_only" :json)
    ("gethdkeys" 0 "options" :json)
    ("gethdkeys" 0 "private" :json)
    ("createwalletdescriptor" 1 "options" :json)
    ("createwalletdescriptor" 1 "internal" :json)
    ("echojson" 0 "arg0" :json)
    ("echojson" 1 "arg1" :json)
    ("echojson" 2 "arg2" :json)
    ("echojson" 3 "arg3" :json)
    ("echojson" 4 "arg4" :json)
    ("echojson" 5 "arg5" :json)
    ("echojson" 6 "arg6" :json)
    ("echojson" 7 "arg7" :json)
    ("echojson" 8 "arg8" :json)
    ("echojson" 9 "arg9" :json)
    ("rescanblockchain" 0 "start_height" :json)
    ("rescanblockchain" 1 "stop_height" :json)
    ("createwallet" 0 "wallet_name" :string)
    ("createwallet" 1 "disable_private_keys" :json)
    ("createwallet" 2 "blank" :json)
    ("createwallet" 3 "passphrase" :string)
    ("createwallet" 4 "avoid_reuse" :json)
    ("createwallet" 5 "descriptors" :json)
    ("createwallet" 6 "load_on_startup" :json)
    ("createwallet" 7 "external_signer" :json)
    ("restorewallet" 0 "wallet_name" :string)
    ("restorewallet" 1 "backup_file" :string)
    ("restorewallet" 2 "load_on_startup" :json)
    ("loadwallet" 0 "filename" :string)
    ("loadwallet" 1 "load_on_startup" :json)
    ("unloadwallet" 0 "wallet_name" :string)
    ("unloadwallet" 1 "load_on_startup" :json)
    ("getnodeaddresses" 0 "count" :json)
    ("addpeeraddress" 1 "port" :json)
    ("addpeeraddress" 2 "tried" :json)
    ("sendmsgtopeer" 0 "peer_id" :json)
    ("stop" 0 "wait" :json)
    ("addnode" 2 "v2transport" :json)
    ("addconnection" 2 "v2transport" :json)
    ("decodepsbt" 0 "psbt" :string)
    ("analyzepsbt" 0 "psbt" :string)
    ("verifymessage" 1 "signature" :string)
    ("verifymessage" 2 "message" :string)
    ("getnewaddress" 0 "label" :string)
    ("getnewaddress" 1 "address_type" :string)
    ("backupwallet" 0 "destination" :string)
    ("echoipc" 0 "arg" :string)
    ("encryptwallet" 0 "passphrase" :string)
    ("getaddressesbylabel" 0 "label" :string)
    ("loadtxoutset" 0 "path" :string)
    ("migratewallet" 0 "wallet_name" :string)
    ("migratewallet" 1 "passphrase" :string)
    ("setlabel" 1 "label" :string)
    ("signmessage" 1 "message" :string)
    ("signmessagewithprivkey" 1 "message" :string)
    ("walletpassphrasechange" 0 "oldpassphrase" :string)
    ("walletpassphrasechange" 1 "newpassphrase" :string)
    )
  "Core vRPCConvertParams: (method position name format), FORMAT one of
:JSON (parse as JSON, fail on bad JSON), :STRING (never parse; listed so
-named does not split a value containing `=') and :JSON-OR-STRING (parse,
and pass the raw text as a string when it is not JSON).")

(defun %convert-from-position (method pos)
  (find-if (lambda (row) (and (string= (first row) method) (= (second row) pos)))
           *rpc-convert-params*))

(defun %convert-from-name (method name)
  (find-if (lambda (row) (and (string= (first row) method) (string= (third row) name)))
           *rpc-convert-params*))

(defun %parse-json-arg (raw format)
  "Core Parse (client.cpp:395-404): RAW as JSON; for :JSON-OR-STRING a failed
parse is the raw string, for :JSON it is `Error parsing JSON: RAW'."
  (handler-case (uv-read raw)
    (json-parse-failure ()
      (if (eq format :json-or-string)
          raw
          (cli-error "Error parsing JSON: ~A" raw)))))

(defun %parse-param (row raw)
  "Core ParseParam (client.cpp:426-430)."
  (if (and row (member (fourth row) '(:json :json-or-string)))
      (%parse-json-arg raw (fourth row))
      raw))

(defun rpc-convert-values (method args)
  "Core RPCConvertValues (client.cpp:435-445): the positional ARGS (strings)
as a params array, each converted by its (METHOD, position) row."
  (cons :arr (loop for s in args
                   for i from 0
                   collect (%parse-param (%convert-from-position method i) s))))

(defun rpc-convert-named-values (method args)
  "Core RPCConvertNamedValues (client.cpp:475-517): -named ARGS as a params
object. An argument without `=' is positional; NAME=VALUE is named unless NAME
is not one of METHOD's listed names AND the next positional slot is a JSON one
the whole argument parses as, or a string one -- the two escapes that let
`[\"key=value\"]' and `my=wallet' through as positional values. A later NAME
overwrites an earlier one in place; positional arguments go last, under
\"args\" -- appended by pushKVEnd even when an explicit args= is there, so the
server sees the key twice."
  (let ((named nil) (positional nil))
    (dolist (s args)
      (let ((eq-pos (position #\= s)))
        (if (null eq-pos)
            (push (%parse-param (%convert-from-position method (length positional)) s)
                  positional)
            (let* ((name (subseq s 0 eq-pos))
                   (value (subseq s (1+ eq-pos)))
                   (named-row (%convert-from-name method name))
                   (pos-row (and (null named-row)
                                 (%convert-from-position method (length positional))))
                   (as-json (and pos-row (eq (fourth pos-row) :json)
                                 (handler-case (uv-read s)
                                   (json-parse-failure () nil)))))
              (cond (as-json (push as-json positional))
                    ((and pos-row (eq (fourth pos-row) :string)) (push s positional))
                    (t
                     (let ((parsed (%parse-param named-row value))
                           (cell (assoc name named :test #'string=)))
                       ;; UniValue::pushKV replaces an existing key in place.
                       (if cell
                           (setf (cdr cell) parsed)
                           (push (cons name parsed) named)))))))))
    (setf named (nreverse named))
    ;; pushKVEnd APPENDS, even when an explicit args= already holds the key:
    ;; the request then names args twice and the server refuses it
    ;; (rpc/server.cpp:374-382), rather than the client silently choosing.
    (when positional
      (setf named (append named (list (cons "args" (cons :arr (nreverse positional)))))))
    (cons :obj named)))
