(in-package #:bitcoin-lisp.config)

;;;; settings.json (Core common/settings.cpp)
;;;
;;; The read-write settings file: the warning key, the values a node may
;;; persist, and their rendering.

;;; --- settings.json (Core's read-write settings file) ---
;;;
;;; Core keeps a JSON object of "read-write" settings in the network directory,
;;; between the command line and the config file in precedence
;;; (common/settings.cpp:36). It is read AND rewritten on every start
;;; (common/init.cpp:98-115), which is how a datadir that has ever been started
;;; always has one.

(defparameter +settings-warning-key+ "_warning_"
  "Core SETTINGS_WARN_MSG_KEY. Stripped on read, re-added on write, and never
visible as a setting.")

(defparameter +client-name+ "bitcoin-lisp"
  "Core's CLIENT_NAME. Named here rather than derived from the user agent
because it is the value scripts/conformance-config.sh publishes to Core's test
framework as CLIENT_NAME, and the framework compares strings with it.")

(defun settings-file-warning ()
  "Core's auto-generated comment, verbatim (common/settings.cpp:129-130)."
  (format nil "This file is automatically generated and updated by ~A. Please ~
do not edit this file while the node is running, as any changes might be ~
ignored or overwritten."
          +client-name+))

(defun render-json-value (value)
  "VALUE as compact JSON, matching UniValue::write() — which is what Core
interpolates into its `Setting file arg:` lines, so the rendering is part of
the log contract rather than a detail.

yason's encoder already produces that form byte for byte, including \\uXXXX for
control characters and `null` for NIL; the values here come straight from
yason's parser, so nothing needs re-tagging on the way in either. Reading a
settings file with PARSE-SETTINGS-JSON and writing it back is a pure round trip
through one library."
  (with-output-to-string (out) (yason:encode value out)))

(defun %json-escape (string)
  "STRING as a JSON string literal, quotes included."
  (render-json-value string))

(defun parse-settings-json (text path-string)
  "Parse settings-file TEXT. Returns (VALUES alist errors), where ALIST maps
setting name to its parsed JSON value and ERRORS is a list of Core's own
message strings — the functional tests match on their wording
(feature_settings.py).

TEXT is parsed TWICE, which is worth the two passes on a file this size. The
:alist pass is the only one that can see a DUPLICATE KEY (a hash-table parse
silently keeps the last, and the node would start on a setting the operator
cannot see in the file) and it preserves the key ORDER Core writes back. The
default pass supplies the VALUES, because only there are the JSON types
unambiguous: as an alist a nested object and an array of pairs are the same
list, and an empty array is NIL, which is also how null arrives.

An error yields NO settings rather than partial ones: Core clears the map on a
duplicate key and returns nothing on a parse failure, and a node that started
with half a settings file applied is worse than one that refused to start."
  (flet ((invalid ()
           (return-from parse-settings-json
             (values nil (list (format nil "Settings file ~A does not contain valid ~
JSON. This is probably caused by disk corruption or a crash, and can be fixed ~
by removing the file, which will reset settings to default values." path-string))))))
    (let ((keyed (handler-case
                     (let ((yason:*parse-object-as* :alist)
                           (yason:*parse-json-booleans-as-symbols* t))
                       (yason:parse text))
                   (error () (invalid))))
          (table nil))
    ;; An alist parse of a non-object gives back the scalar itself, and a JSON
    ;; array parses to a LIST — shaped exactly like an alist of nothing, so
    ;; emptiness alone cannot tell them apart. The test is that every element
    ;; is a (string . value) cons.
    (unless (and (listp keyed)
                 (every (lambda (c) (and (consp c) (stringp (car c)))) keyed))
      (return-from parse-settings-json
        (values nil (list (format nil "Found non-object value ~A in settings file ~A"
                                  (render-json-value keyed) path-string)))))
    ;; Duplicate keys BEFORE the second parse: yason's hash-table parser
    ;; signals on one, and the handler would report it as invalid JSON —
    ;; losing the message Core prints and the test matches on.
    (let ((seen (make-hash-table :test 'equal)))
      (dolist (cell keyed)
        (when (gethash (car cell) seen)
          (return-from parse-settings-json
            (values nil (list (format nil "Found duplicate key ~A in settings file ~A"
                                      (car cell) path-string)))))
        (setf (gethash (car cell) seen) t)))
    (setf table (handler-case
                    (let ((yason:*parse-json-arrays-as-vectors* t)
                          (yason:*parse-json-booleans-as-symbols* t))
                      (yason:parse text))
                  (error () (invalid))))
    (let ((out nil))
      (dolist (cell keyed)
        (unless (string= (car cell) +settings-warning-key+)
          (push (cons (car cell) (gethash (car cell) table)) out)))
      (values (nreverse out) nil)))))

(defun render-settings-json (alist)
  "ALIST as the text of a settings file: the warning comment first, then every
setting in the order given (Core WriteSettings, common/settings.cpp:123-142)."
  (with-output-to-string (out)
    (format out "{~%    ~A: ~A"
            (%json-escape +settings-warning-key+)
            (%json-escape (settings-file-warning)))
    (dolist (cell alist)
      (format out ",~%    ~A: ~A"
              (%json-escape (car cell)) (render-json-value (cdr cell))))
    (format out "~%}~%")))

(defun settings-alist->config-alist (settings)
  "SETTINGS (name -> parsed JSON value) as the (name . string) cells the rest
of the config layer speaks. A JSON false is Core's negation, i.e. \"0\"."
  (loop for (name . value) in settings
        collect (cons name
                      (cond ((eq value 'yason:false) "0")
                            ((eq value 'yason:true) "1")
                            ((null value) "0")
                            ((stringp value) value)
                            (t (render-json-value value))))))

(defun validate-settings-values (settings)
  "The Core-worded init error a settings file's VALUES earn, or NIL.

Only -wallet is checked, because it is the only setting whose JSON TYPE Core
validates rather than coercing: every element of the wallet list must be a
string, and anything else is a fatal init error (wallet/load.cpp:81-86,
121-126). A settings file is written by software, so a wrong type there is not
a typo — it is a corrupted or hand-edited file, and loading a wallet named
`true` is worse than refusing to start."
  (let ((cell (assoc "wallet" settings :test #'string=)))
    (when cell
      (let* ((value (cdr cell))
             (elements (cond
                         ;; A JSON false is -nowallet: no names at all, valid.
                         ((eq value 'yason:false) nil)
                         ((stringp value) (list value))
                         ((or (vectorp value) (and (listp value) value))
                          (coerce value 'list))
                         (t (list value)))))
        (unless (every #'stringp elements)
          "Invalid value detected for '-wallet' or '-nowallet'. '-wallet' requires a string value, while '-nowallet' accepts only '1' to disable all wallets")))))

(defun unknown-settings-keys (settings)
  "The settings-file keys no option table recognizes. Core logs one warning
each and carries on (args.cpp:420-423) — unknown settings never abort startup."
  (unknown-config-file-keys settings))
