;;;; Package bitcoin-lisp.mempool -- the public API of src/mempool/.
;;;;
;;;; Loaded with the other package files before any code (bitcoin-lisp.asd,
;;;; the "packages" phase): src/config.lisp loads third and already names
;;;; most of these packages, and every package must exist before
;;;; src/package.lisp installs the bl.* nicknames. Add an export here when a
;;;; definition in src/mempool/ becomes API; keep %-prefixed names internal.

(defpackage #:bitcoin-lisp.mempool
  (:use #:cl #:bitcoin-lisp.conditions)
  (:export
   ;; Constants
   #:+default-max-mempool-bytes+
   #:*max-mempool-bytes*
   #:+default-min-relay-fee-rate+
   #:+fee-history-size+
   #:+min-blocks-for-estimate+
   #:+fee-stats-flush-interval+
   ;; FeeFrac (Core util/feefrac.{h,cpp})
   #:feefrac
   #:make-feefrac
   #:copy-feefrac
   #:feefrac-p
   #:feefrac-fee
   #:feefrac-size
   #:feefrac-empty-p
   #:feefrac+
   #:feefrac-
   #:feefrac=
   #:feerate-compare
   #:feefrac<<
   #:feefrac>>
   #:feefrac-compare
   #:feefrac<
   #:feefrac>
   #:feefrac<=
   #:feefrac>=
   #:feefrac-evaluate-fee-down
   #:feefrac-evaluate-fee-up
   #:compare-chunks
   ;; Cluster linearization (Core cluster_linearize.h)
   #:+max-cluster-count+
   #:do-bits
   #:depgraph
   #:make-depgraph
   #:depgraph-p
   #:depgraph-positions
   #:depgraph-position-range
   #:depgraph-tx-count
   #:depgraph-tx-feerate
   #:depgraph-ancestors
   #:depgraph-descendants
   #:depgraph-add-transaction
   #:depgraph-remove-transactions
   #:depgraph-add-dependencies
   #:depgraph-reduced-parents
   #:depgraph-reduced-children
   #:depgraph-subset-feerate
   #:depgraph-connected-component
   #:depgraph-find-connected-component
   #:depgraph-connected-p
   #:depgraph-acyclic-p
   #:depgraph-topo-sorted
   #:topological-subset-p
   #:linearization-topological-p
   #:setinfo
   #:make-setinfo
   #:setinfo-transactions
   #:setinfo-feerate
   #:chunk-linearization
   #:chunk-linearization-info
   #:ancestor-sort-linearization
   #:post-linearize
   #:linearize
   ;; TxGraph (Core txgraph.{h,cpp})
   #:+max-cluster-size+
   #:txgraph
   #:make-txgraph
   #:txgraph-p
   #:txgraph-tx-count
   #:txgraph-oversized-p
   #:tx-handle
   #:tx-handle-p
   #:tx-handle-id
   #:tx-handle-data
   #:txgraph-add-transaction
   #:txgraph-remove-transaction
   #:txgraph-add-dependency
   #:txgraph-add-dependencies
   #:txgraph-set-transaction-fee
   #:txgraph-exists-p
   #:txgraph-get-individual-feerate
   #:txgraph-get-main-chunk-feerate
   #:txgraph-get-cluster
   #:txgraph-get-cluster-chunks
   #:txgraph-get-ancestors
   #:txgraph-get-descendants
   #:txgraph-get-ancestors-union
   #:txgraph-get-descendants-union
   #:txgraph-compare-main-order
   #:txgraph-count-distinct-clusters
   #:txgraph-rbf-diagrams
   #:txgraph-package-rbf-diagrams
   #:txgraph-get-worst-main-chunk
   #:txgraph-trim
   #:txgraph-sanity-check
   #:block-builder
   #:block-builder-p
   #:make-block-builder
   #:block-builder-current-chunk
   #:block-builder-current-chunk-feerate
   #:block-builder-include
   #:block-builder-skip
   #:block-builder-finish
   ;; Mempool entry
   #:mempool-entry
   #:make-mempool-entry
   #:make-entry-from-tx
   #:sigop-adjusted-vsize
   #:mempool-entry-transaction
   #:mempool-entry-fee
   #:mempool-entry-modified-fee
   #:mempool-deltas
   #:mempool-prioritise
   #:mempool-unbroadcast
   #:mempool-add-unbroadcast
   #:mempool-remove-unbroadcast
   #:mempool-unbroadcast-txids
   #:mempool-unbroadcast-count
   #:mempool-unbroadcast-p
   #:mempool-dat-path
   #:save-mempool-file
   #:read-mempool-file
   #:mempool-entry-size
   #:mempool-entry-usage
   #:mempool-entry-vsize
   #:mempool-entry-wtxid
   #:mempool-entry-sigops
   #:mempool-entry-height
   #:mempool-entry-entry-time
   #:mempool-entry-sequence
   #:mempool-sequence
   #:mempool-transactions-updated
   #:bpe-estimate-raw-fee
   #:horizon-max-confirms
   #:mempool-entry-fee-rate
   ;; Mempool entry links
   #:mempool-entry-parents
   #:mempool-entry-children
   #:mempool-entry-graph-handle
   ;; Mempool
   #:mempool
   #:make-mempool
   #:mempool-graph
   #:*txgraph-shadow-checks*
   #:mempool-by-wtxid
   #:mempool-find-parents
   #:single-truc-checks
   #:+truc-version+
   #:+truc-max-vsize+
   #:+truc-child-max-vsize+
   #:+truc-ancestor-limit+
   #:mempool-ancestors
   #:mempool-descendants
   #:mempool-ancestor-stats
   #:mempool-descendant-stats
   #:mempool-ancestor-fee-rate
   #:mempool-descendant-fee-rate
   #:mempool-remove-recursive
   #:mempool-expire
   #:*mempool-expiry-hours*
   #:*min-relay-fee-rate*
   #:mempool-trim-to-size
   #:*cluster-count-limit*
   #:*cluster-size-limit*
   #:mempool-effective-min-fee-rate
   #:mempool-decayed-rolling-min-fee-rate
   #:mempool-orphan-pool
   ;; Orphan pool (Core TxOrphanage at d3056bc: wtxid-keyed, per-peer
   ;; announcement accounting, DoS-bounded eviction, no time expiry)
   #:make-orphan-pool
   #:orphan-pool-count
   #:orphan-entry-transaction
   #:orphan-add
   #:orphan-remove
   #:orphan-tx
   #:orphan-have
   #:orphan-have-from-peer
   #:orphan-announcers
   #:orphan-children-from-peer
   #:orphans-depending-on
   #:orphan-erase-for-peer
   #:orphan-erase-for-block
   #:orphan-total-usage
   #:orphan-total-latency-score
   #:orphan-usage-by-peer
   #:orphan-announcements-from-peer
   #:+max-orphanage-latency-score+
   #:+reserved-orphan-weight-per-peer+
   #:tx-signals-rbf-p
   #:find-rbf-conflicts
   #:check-rbf-rules
   #:check-package-rbf-rules
   #:*mempool-full-rbf*
   #:mempool-has
   #:mempool-get
   #:mempool-get-by-wtxid
   #:mempool-spending-tx
   #:mempool-add
   #:accept-validated-tx
   #:mempool-remove
   #:*mempool-removal-reason*
   #:mempool-count
   #:mempool-total-size
   #:mempool-dynamic-usage
   #:transaction-dynamic-usage
   #:mempool-min-fee-rate
   #:mempool-check-conflict
   #:mempool-package-fits-cluster-limits-p
   #:mempool-remove-for-block
   #:mempool-remove-spenders
   #:mempool-update-for-reorg
   #:mempool-get-transactions
   #:mempool-for-each
   ;; Block fee stats
   #:block-fee-stats
   #:make-block-fee-stats
   #:block-fee-stats-height
   #:block-fee-stats-median-rate
   #:block-fee-stats-low-rate
   #:block-fee-stats-high-rate
   #:block-fee-stats-tx-count
   ;; Fee estimator
   #:fee-estimator
   #:make-fee-estimator
   #:fee-estimator-entry-count
   #:fee-estimator-data-directory
   #:fee-estimator-blocks-since-flush
   #:fee-estimator-add-stats
   #:fee-estimator-ready-p
   #:fee-estimator-get-history
   #:calculate-tx-fee-rate
   #:compute-block-fee-stats
   ;; Fee stats persistence
   #:save-fee-stats
   #:load-fee-stats
   #:maybe-flush-fee-stats
   ;; Core CBlockPolicyEstimator (G7-21)
   #:*block-policy-estimator*
   #:make-block-policy-estimator
   #:bpe-note-entry
   #:bpe-note-removal
   #:bpe-note-block
   #:bpe-smart-fee-sat-per-vb
   #:bpe-estimate-smart-fee
   #:bpe-write-to-stream
   #:bpe-read-into
   #:*accept-stale-fee-estimates*
   ;; Fee estimation
   #:estimate-fee-rate
   #:highest-target-tracked))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (bitcoin-lisp.nicknames:install-package-nicknames))
