(in-package #:bitcoin-lisp.networking)

;;;; Minisketch — set reconciliation sketches over GF(2^32)
;;;;
;;;; A sketch is a fixed-size "set checksum" with two properties nothing else
;;;; has: XORing two sketches gives a sketch of the two sets' SYMMETRIC
;;;; DIFFERENCE, and a sketch of capacity c recovers any difference of up to c
;;;; elements. That is what makes BIP-330 reconciliation cheaper than
;;;; announcing every transaction to every peer.
;;;;
;;;; The library Core vendors, refs/bitcoin/src/minisketch/, at the 32-bit
;;;; field its wrapper uses (node/minisketchwrapper.cpp:22). The format is a
;;;; capacity-c sketch of the ODD power sums [s1, s3, ..., s(2c-1)], each a
;;;; 32-bit field element, serialized little-endian (sketch_impl.h:376-392,
;;;; BitWriter). Construction, merge and serialization follow minisketch.h's
;;;; API contract; the decoder below is a port of sketch_impl.h, verdict for
;;;; verdict, and the field's generic multiply and squaring stand in for the
;;;; library's table-driven and CLMUL fast paths, which are speed, not format.
;;;;
;;;; Oracle: tests/data/minisketch_core_vectors.json, generated by Core's
;;;; vendored pyminisketch.py (src/minisketch/tests/, the authors' Python
;;;; reimplementation of the library's algorithms) with
;;;; tests/data/minisketch_core_vectors.py -- field products and inverses,
;;;; serialized sketches, Core's own minisketch_tests.cpp reconciliation
;;;; scenario, and 116 decode verdicts including every failure shape -- plus
;;;; the C library's own SQR_TABLE_32 / QRT_TABLE_32 constants
;;;; (fields/generic_4bytes.cpp:88-89). The C++ library itself cannot be
;;;; compiled in the project container (the runtime image has no C++
;;;; compiler), so that residual is between pyminisketch and the C library.

;;;; --- GF(2^32) -----------------------------------------------------------

(defconstant +ms-field-bits+ 32)
(defconstant +ms-field-mask+ #xFFFFFFFF)

(defconstant +ms-field-modulus+ #x8D
  "The reduction polynomial x^32 + x^7 + x^3 + x^2 + 1, with the x^32 term
implied. Minisketch's own choice for the 32-bit field
(fields/generic_4bytes.cpp:90: Field<uint32_t, 32, 141, ...>) — and the field
size BIP-330 uses, since a 32-bit short ID is what gets reconciled.")

(declaim (inline ms-add))
(defun ms-add (a b)
  "Addition in a characteristic-2 field is XOR, and so is subtraction — which
is why two sketches combine into a sketch of the symmetric difference by
XORing, and why an element added twice cancels itself out."
  (logxor a b))

(defun ms-mul (a b)
  "Carry-less multiply, reduced by the field polynomial."
  (declare (type (unsigned-byte 32) a b)
           (optimize (speed 3) (safety 1)))
  (let ((r 0))
    (declare (type (unsigned-byte 32) r))
    (loop while (plusp b)
          do (when (logbitp 0 b) (setf r (logxor r a)))
             (setf b (ash b -1))
             (let ((carry (logbitp (1- +ms-field-bits+) a)))
               (setf a (logand (ash a 1) +ms-field-mask+))
               (when carry (setf a (logxor a +ms-field-modulus+)))))
    r))

(defun ms-mul2 (a)
  "Multiply by x: the library's Field::Mul2, one LFSR step (int_utils.h LFSR)."
  (ms-mul a 2))

(declaim (inline ms-sqr))
(defun ms-sqr (a) (ms-mul a a))

(defun ms-pow (a e)
  "Exponentiation by squaring."
  (let ((r 1))
    (loop while (plusp e)
          do (when (logbitp 0 e) (setf r (ms-mul r a)))
             (setf a (ms-sqr a))
             (setf e (ash e -1)))
    r))

(defun ms-inv (a)
  "Multiplicative inverse, by Fermat: a^(2^32 - 2).

The library uses an extended GCD (int_utils.h InvExtGCD); the inverse is
unique, so the method is speed, not format. Decoding needs a handful of
inverses per recovered element, so the ~32 squarings and ~31 multiplies are
not worth a second implementation to get wrong."
  (assert (plusp a) () "zero has no inverse in GF(2^~D)" +ms-field-bits+)
  (ms-pow a (- (ash 1 +ms-field-bits+) 2)))

;;;; --- Sketches -----------------------------------------------------------

(defun ms-make-sketch (capacity)
  "An empty sketch: CAPACITY odd power sums, all zero."
  (make-array capacity :element-type '(unsigned-byte 32) :initial-element 0))

(defun ms-sketch-add (sketch element)
  "Fold ELEMENT into SKETCH, in place: minisketch_add_uint64
(minisketch.h:117-130, sketch_impl.h AddToOddSyndromes).

Adds m, m^3, m^5, ... to the accumulators. Only the ODD powers are stored,
because in characteristic 2 the even ones are free: s(2i) = s(i)^2, since
squaring is additive here. That halves the sketch, making it exactly as large
as sending the elements themselves would be — which is the whole economy of the
scheme.

The library's contract, which this keeps: an element wider than the field
loses its high bits (Field::FromUint64 masks), and 0 -- after the masking --
is a no-op, since its powers are all zero. A sketch cannot hold 0, which is why
BIP-330 short IDs start at 1."
  (let* ((element (logand element +ms-field-mask+))
         (p element)
         (sq (ms-sqr element)))
    (unless (zerop element)
      (dotimes (i (length sketch))
        (setf (aref sketch i) (ms-add (aref sketch i) p))
        (setf p (ms-mul p sq))))
    sketch))

(defun ms-sketch-merge (a b)
  "The sketch of the symmetric difference of A's and B's sets:
minisketch_merge (minisketch.h:132-148, sketch_impl.h Merge). A capacity
mismatch is not an error there: the result has the SMALLER capacity, the
syndromes both sketches carry."
  (let ((out (ms-make-sketch (min (length a) (length b)))))
    (dotimes (i (length out) out)
      (setf (aref out i) (ms-add (aref a i) (aref b i))))))

(defun ms-sketch-serialize (sketch)
  "Wire form: each term as a little-endian 32-bit word (the library's BitWriter
at 32 bits per element; BIP-330's `4c-byte serialization')."
  (let ((out (make-array (* 4 (length sketch)) :element-type '(unsigned-byte 8))))
    (dotimes (i (length sketch) out)
      (let ((v (aref sketch i)))
        (setf (aref out (* 4 i)) (ldb (byte 8 0) v)
              (aref out (+ (* 4 i) 1)) (ldb (byte 8 8) v)
              (aref out (+ (* 4 i) 2)) (ldb (byte 8 16) v)
              (aref out (+ (* 4 i) 3)) (ldb (byte 8 24) v))))))

(defun ms-sketch-deserialize (bytes)
  (assert (zerop (mod (length bytes) 4)) () "sketch length must be a multiple of 4")
  (let* ((n (floor (length bytes) 4))
         (sketch (ms-make-sketch n)))
    (dotimes (i n sketch)
      (setf (aref sketch i)
            (logior (aref bytes (* 4 i))
                    (ash (aref bytes (+ (* 4 i) 1)) 8)
                    (ash (aref bytes (+ (* 4 i) 2)) 16)
                    (ash (aref bytes (+ (* 4 i) 3)) 24))))))

;;;; --- Decoding -----------------------------------------------------------
;;;;
;;;; A port of the library's own decoder, sketch_impl.h:16-373 (PolyMod,
;;;; DivMod, MakeMonic, GCD, Sqr, TraceMod, RecFindRoots, FindRoots,
;;;; BerlekampMassey, ReconstructAllSyndromes, SketchImpl::Decode), shape for
;;;; shape. The verdict is the contract: which sketches decode, to which set,
;;;; and which FAIL -- a decoder that is merely mathematically right answers
;;;; the over-full and malformed sketches a peer can send differently, and it
;;;; did (an LFSR longer than the capacity indexed past its coefficient
;;;; vector). Polynomials are adjustable vectors of field elements, low
;;;; coefficient first, standing in for the library's std::vector.

(alexandria:define-constant +ms-qrt-table+
    (coerce '(#x54fd1264 #xc26fcd64 #xc26fcd66 #x238a7462 #xc26fcd62 #x973bccaa
              #x238a746a #x77766712 #xc26fcd72 #xc1bdd556 #x973bcc8a #x572a094c
              #x238a742a #xb693be84 #x77766792 #x9555c03e #xc26fcc72 #x568419f8
              #xc1bdd756 #x96c3d2ca #x973bc88a #x54861fdc #x572a014c #xb79badc4
              #x238a642a #xb9b99fe0 #xb6939e84 #xc519fa86 #x77762792 0
              #x9555403e #x377627ba)
            '(simple-array (unsigned-byte 32) (32)))
  :test 'equalp
  :documentation "The library's QRT_TABLE_32 (fields/generic_4bytes.cpp:89): the image of each
basis bit under the GF(2)-linear map Qrt, which solves r^2 + r = a for every a
of trace zero. The quadratic step of the root finder uses it.")

(defun ms-qrt (a)
  "Field::Qrt (generic_common_impl.h:40): a root r of r^2 + r = A, found by
the linear map +MS-QRT-TABLE+. Undefined (some element that fails the check)
when A has trace one, which is why every caller checks the answer."
  (let ((r 0))
    (dotimes (i +ms-field-bits+ r)
      (when (logbitp i a)
        (setf r (logxor r (aref +ms-qrt-table+ i)))))))

(defun %ms-poly (&rest coefficients)
  (let ((p (make-array (length coefficients) :element-type '(unsigned-byte 32)
                                             :adjustable t
                                             :fill-pointer (length coefficients))))
    (replace p coefficients)))

(defun %ms-poly-copy (p)
  (let ((c (make-array (length p) :element-type '(unsigned-byte 32)
                                  :adjustable t :fill-pointer (length p))))
    (replace c p)))

(defun %ms-poly-resize (p n)
  "std::vector::resize: shrink, or grow with zeros. P is changed in place."
  (let ((old (length p)))
    (when (> n (array-dimension p 0))
      (adjust-array p (max n (* 2 (array-dimension p 0)))))
    (setf (fill-pointer p) n)
    (loop for i from old below n do (setf (aref p i) 0))
    p))

(defun %ms-poly-trim (p)
  "Drop trailing zero coefficients, in place."
  (loop while (and (plusp (length p)) (zerop (aref p (1- (length p)))))
        do (decf (fill-pointer p)))
  p)

(defun %ms-poly-reduce-top (mod val)
  "The shared step of PolyMod and DivMod: pop VAL's top term and subtract that
multiple of the monic MOD, aligned under it. Returns the popped term."
  (let ((term (vector-pop val)))
    (unless (zerop term)
      (let ((base (1+ (- (length val) (length mod)))))
        (dotimes (x (1- (length mod)))
          (setf (aref val (+ base x))
                (logxor (aref val (+ base x)) (ms-mul term (aref mod x)))))))
    term))

(defun %ms-poly-mod (mod val)
  "PolyMod (sketch_impl.h:16-33): VAL := VAL mod MOD, in place; MOD is monic."
  (when (>= (length val) (length mod))
    (loop while (>= (length val) (length mod))
          do (%ms-poly-reduce-top mod val))
    (%ms-poly-trim val))
  val)

(defun %ms-poly-divmod (mod val div)
  "DivMod (sketch_impl.h:35-57): the quotient VAL / MOD into DIV, the remainder
left in VAL; both in place, MOD monic."
  (if (< (length val) (length mod))
      (setf (fill-pointer div) 0)
      (progn
        (%ms-poly-resize div (1+ (- (length val) (length mod))))
        (loop while (>= (length val) (length mod))
              do (setf (aref div (- (length val) (length mod)))
                       (aref val (1- (length val))))
                 (%ms-poly-reduce-top mod val))))
  div)

(defun %ms-make-monic (a)
  "MakeMonic (sketch_impl.h:59-71): scale A in place so its top coefficient is 1."
  (let ((top (aref a (1- (length a)))))
    (unless (= top 1)
      (let ((inv (ms-inv top)))
        (setf (aref a (1- (length a))) 1)
        (dotimes (i (1- (length a)))
          (setf (aref a i) (ms-mul (aref a i) inv))))))
  a)

(defun %ms-poly-gcd (a b)
  "GCD (sketch_impl.h:73-87). Destroys both arguments; returns the gcd, which is
monic unless the loop never ran (B was the zero polynomial)."
  (when (< (length a) (length b)) (rotatef a b))
  (loop while (plusp (length b))
        do (when (= (length b) 1)
             (return-from %ms-poly-gcd (%ms-poly 1)))
           (%ms-make-monic b)
           (%ms-poly-mod b a)
           (rotatef a b))
  a)

(defun %ms-poly-sqr (poly)
  "Sqr (sketch_impl.h:89-98): square POLY in place. Squaring is additive in
characteristic 2, so it is squaring every coefficient and spreading them to
the even positions."
  (let ((n (length poly)))
    (when (plusp n)
      (%ms-poly-resize poly (1- (* 2 n)))
      (loop for x from (1- (length poly)) downto 0
            do (setf (aref poly x)
                     (if (oddp x) 0 (ms-sqr (aref poly (floor x 2))))))))
  poly)

(defun %ms-trace-mod (mod param)
  "TraceMod (sketch_impl.h:100-113): Tr(PARAM*x) mod MOD, where Tr(y) = y + y^2
+ y^4 + ... + y^(2^31). The trace of a field element is 0 or 1, so a gcd with
it collects the roots whose trace under PARAM is zero -- the splitting step."
  (let ((out (%ms-poly 0 param)))
    (dotimes (i (1- +ms-field-bits+) out)
      (%ms-poly-sqr out)
      (when (< (length out) 2) (%ms-poly-resize out 2))
      (setf (aref out 1) param)
      (%ms-poly-mod mod out))))

(defun %ms-factorizable-p (trace poly)
  "RecFindRoots's fail-fast test (sketch_impl.h:165-208): trace + trace^2 is
RANDV*(x + x^(2^32)) mod POLY, which is zero exactly when POLY divides
x^(2^32) - x, i.e. splits into distinct linear factors."
  (let ((tmp (%ms-poly-sqr (%ms-poly-copy trace))))
    (dotimes (i (length trace))
      (setf (aref tmp i) (logxor (aref tmp i) (aref trace i))))
    (%ms-poly-trim tmp)
    (%ms-poly-mod poly tmp)
    (zerop (length tmp))))

(defun %ms-rec-find-roots (poly fully-factorizable depth randv)
  "RecFindRoots (sketch_impl.h:115-257): the roots of the monic, square-free
POLY. Returns (VALUES roots ok-p); OK-P false means POLY does not split into
distinct linear factors, which is the decoder's failure verdict.

RANDV is doubled on every attempt, so the attempts form a GF(2)-linearly
independent basis and at most 32 of them are ever needed; the degree check
against DEPTH is the library's own bound on a split that should have
happened. POLY is consumed."
  (let ((n (length poly)))
    (cond
      ((= n 2) (values (list (aref poly 0)) t))
      ((= n 3)
       ;; x^2 + a has a double root: not square-free.
       (if (zerop (aref poly 1))
           (values nil nil)
           (let* ((input (ms-mul (aref poly 0) (ms-sqr (ms-inv (aref poly 1)))))
                  (root (ms-qrt input)))
             (if (/= (logxor (ms-sqr root) root) input)
                 (values nil nil)
                 (let ((sol (ms-mul root (aref poly 1))))
                   (values (list sol (logxor sol (aref poly 1))) t))))))
      (t
       (let (trace)
         (loop for iter from 0
               do (setf trace (%ms-trace-mod poly randv))
                  (when (and (>= iter 1) (not fully-factorizable))
                    (unless (%ms-factorizable-p trace poly)
                      (return-from %ms-rec-find-roots (values nil nil)))
                    (setf fully-factorizable t))
                  (when (and fully-factorizable
                             (/= 0 (ash (- n 2) (- depth +ms-field-bits+))))
                    (return-from %ms-rec-find-roots (values nil nil)))
                  (incf depth)
                  (setf randv (ms-mul2 randv))
                  (setf trace (%ms-poly-gcd trace (%ms-poly-copy poly)))
                  (when (and (/= (length trace) n) (> (length trace) 1))
                    (return)))
         (%ms-make-monic trace)
         (let ((quotient (%ms-poly)))
           (%ms-poly-divmod trace poly quotient)
           (multiple-value-bind (roots ok)
               (%ms-rec-find-roots quotient fully-factorizable depth randv)
             (if (not ok)
                 (values nil nil)
                 ;; TRACE holds only roots of trace zero, never an irreducible
                 ;; factor, so it is known to split (the library asserts it).
                 (multiple-value-bind (more ok2)
                     (%ms-rec-find-roots trace t depth randv)
                   (values (append roots more) ok2))))))))))

(defun %ms-find-roots (poly basis)
  "FindRoots (sketch_impl.h:259-281): every root of POLY, or NIL when it does
not split into distinct linear factors."
  (when (> (length poly) 1)
    (multiple-value-bind (roots ok)
        (%ms-rec-find-roots (%ms-poly-copy poly) nil 0 basis)
      (when (and ok (= (length roots) (1- (length poly))))
        roots))))

(defun %ms-berlekamp-massey (syndromes max-degree)
  "BerlekampMassey (sketch_impl.h:283-320): the connection polynomial (low
coefficient first, constant term 1) of the shortest LFSR generating
SYNDROMES, or NIL once its degree would pass MAX-DEGREE -- the library stops
there instead of building a longer one, so an over-full sketch costs the
decoder no more than a full one."
  (let ((current (%ms-poly 1))
        (prev (%ms-poly 1))
        (b 1) (b-inv 1) (b-have-inv t))
    (dotimes (n (length syndromes))
      (let ((discrepancy (aref syndromes n)))
        (loop for i from 1 below (length current)
              do (setf discrepancy
                       (logxor discrepancy
                               (ms-mul (aref syndromes (- n i)) (aref current i)))))
        (unless (zerop discrepancy)
          (let ((x (- (1+ n) (1- (length current)) (1- (length prev))))
                (swap (<= (* 2 (1- (length current))) n))
                (tmp nil))
            (unless b-have-inv
              (setf b-inv (ms-inv b) b-have-inv t))
            (when swap
              (when (> (+ (length prev) x -1) max-degree)
                (return-from %ms-berlekamp-massey nil))
              (setf tmp (%ms-poly-copy current))
              (%ms-poly-resize current (+ (length prev) x)))
            (let ((mul (ms-mul discrepancy b-inv)))
              (dotimes (i (length prev))
                (setf (aref current (+ i x))
                      (logxor (aref current (+ i x)) (ms-mul mul (aref prev i))))))
            (when swap
              (setf prev tmp b discrepancy b-have-inv nil))))))
    (when (and (plusp (length current))
               (/= 0 (aref current (1- (length current)))))
      current)))

(defun %ms-all-syndromes (sketch)
  "ReconstructAllSyndromes (sketch_impl.h:322-331): s1..s2c from the c odd ones
that were transmitted, since s(2i) = s(i)^2 in characteristic 2."
  (let ((all (make-array (* 2 (length sketch)) :element-type '(unsigned-byte 32)
                                                :initial-element 0)))
    (dotimes (i (length sketch) all)
      (setf (aref all (* 2 i)) (aref sketch i)
            (aref all (1+ (* 2 i))) (ms-sqr (aref all i))))))

(defun ms-decode (sketch &key (max-elements (length sketch)))
  "Decode SKETCH: SketchImpl::Decode (sketch_impl.h:396-411), minisketch_decode's
contract (minisketch.h:150-157). Returns (VALUES elements ok-p).

OK-P is the verdict, and it has to be a second value: the EMPTY set is a
successful decode (two sides that hold the same transactions cancel to a zero
sketch) and a failed one also has no elements, and a Lisp empty list is NIL
either way. OK-P false -- the library's -1 -- is the ordinary answer for a
difference larger than the capacity or MAX-ELEMENTS, and BIP-330 answers it
with an extension round, not an error.

A successful decode of a set LARGER than the capacity can still return a
different, smaller set with the same sketch ({1,2,3,4,5} and {6,7} share a
capacity-2 sketch). The library does not check for that and cannot; the
protocol above treats a decoded difference as a claim to be settled by the
exchange that follows. The locator's roots, once it splits into distinct
factors of degree at most the capacity, always reproduce the sketch, so no
re-sketch check is needed here either.

The elements come back as the roots of the REVERSED locator, which are the
elements themselves rather than their inverses."
  (let ((poly (%ms-berlekamp-massey (%ms-all-syndromes sketch) max-elements)))
    (cond
      ((null poly) (values nil nil))
      ((= (length poly) 1) (values '() t))
      ((> (length poly) (1+ max-elements)) (values nil nil))
      (t
       (let ((roots (%ms-find-roots (reverse poly)
                                    ;; The splitting basis: the library draws
                                    ;; it at random (SketchImpl's m_basis) and
                                    ;; it changes only the path, never the set.
                                    (1+ (random +ms-field-mask+)))))
         (if roots
             (values roots t)
             (values nil nil)))))))
