#!/usr/bin/env bash
# Generate test/config.ini so Bitcoin Core's functional test framework can find
# this node's binary, and point BITCOIND at it.
#
# Usage:
#   scripts/build-node.sh                 # produces build/bitcoin-lisp-node
#   scripts/conformance-config.sh         # writes test/config.ini
#
# The framework resolves each binary as $BUILDDIR/bin/<name>$EXEEXT unless the
# matching environment variable overrides it (util.py:317-343), so the layout
# below places our single binary where it looks for `bitcoind`.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
BIN="${1:-$ROOT/build/bitcoin-lisp-node}"

if [ ! -x "$BIN" ]; then
  echo "No node binary at $BIN — run scripts/build-node.sh first." >&2
  exit 1
fi

# BUILDDIR/bin/bitcoind is where the framework looks; symlink rather than copy
# so a rebuild is picked up without regenerating anything.
#
# RELATIVE, deliberately. The framework runs inside the project container where
# the repo is mounted at /workspace, so an absolute host path here dangles the
# moment the config is used the way it is meant to be used.
mkdir -p "$ROOT/build/bin"
ln -sf "../$(basename "$BIN")" "$ROOT/build/bin/bitcoind"

# Paths written INTO config.ini are resolved by whoever reads it, which is
# python inside the container. CONFORMANCE_ROOT lets the caller say where the
# repo will be seen from there; it defaults to the host path so running the
# generator by hand still produces something usable.
CONFIG_ROOT="${CONFORMANCE_ROOT:-$ROOT}"

cat > "$ROOT/test/config.ini" <<EOF
# Generated by scripts/conformance-config.sh — do not edit by hand.
#
# Read by Bitcoin Core's test/functional/test_runner.py, which this project
# uses as a behavioural oracle (docs/next-wave-2026-08-22.md track B).

[environment]
CLIENT_NAME=bitcoin-lisp
CLIENT_BUGREPORT=https://github.com/samdefmacro/bitcoin-lisp/issues
SRCDIR=$CONFIG_ROOT/refs/bitcoin
BUILDDIR=$CONFIG_ROOT/build
EXEEXT=
RPCAUTH=$CONFIG_ROOT/refs/bitcoin/share/rpcauth/rpcauth.py

[components]
# Only the node is ours. bitcoin-cli, bitcoin-tx, bitcoin-util, the wallet tool
# and the fuzz/bench binaries do not exist here, so the tests that need them
# are out of scope rather than failing (see the plan's classification).
ENABLE_BITCOIND=true
ENABLE_WALLET=true
ENABLE_ZMQ=true
EOF

echo "Wrote $ROOT/test/config.ini"
echo "Run Core's suite with, for example:"
echo "  BITCOIND=$ROOT/build/bin/bitcoind \\"
echo "    python3 $ROOT/refs/bitcoin/test/functional/rpc_uptime.py \\"
echo "      --configfile=$ROOT/test/config.ini"
