;;;; Package bitcoin-lisp.storage -- the public API of src/storage/.
;;;;
;;;; First component of the bitcoin-lisp/storage sub-system (bitcoin-lisp.asd):
;;;; the package exists before any file in src/storage/ compiles, and the
;;;; INSTALL-PACKAGE-NICKNAMES call at the end of this file gives those files
;;;; their bl.* prefixes. Add an export here when a definition in src/storage/
;;;; becomes API; keep %-prefixed names internal.

(defpackage #:bitcoin-lisp.storage
  (:use #:cl #:bitcoin-lisp.conditions #:bitcoin-lisp.kv)
  (:export
   ;; Block store
   #:block-store
   #:make-block-store
   #:init-block-store
   #:*flat-block-files*
   #:*prune-locks*
   #:+prune-lock-buffer+
   #:register-prune-lock
   #:clear-prune-locks
   #:prune-lock-ceiling
   #:*fast-prune*
   #:*blocks-xor*
   #:max-blockfile-size
   #:block-flat-file-number
   #:store-undo-flat
   #:read-undo-flat
   #:block-file-info
   #:block-file-info-blocks
   #:block-file-info-size
   #:block-file-info-height-first
   #:block-file-info-height-last
   #:block-store-file-info
   #:rebuild-block-file-info
   #:reindex-block-index
   #:migrate-blocks-to-flat-files
   ;; Core datadir layout (kv/datadir.lisp)
   #:datadir-block-index-path
   #:datadir-header-index-file
   #:datadir-index-path
   #:datadir-layout-report
   #:migrate-datadir-layout
   #:count-legacy-blocks
   #:prune-flat-block-file
   #:store-block
   #:get-block
   #:block-exists-p
   ;; Block pruning
   #:prune-block
   #:forget-block-body
   #:ensure-genesis-on-disk
   #:map-external-block-file
   #:+max-block-serialized-size+
   #:block-store-total-bytes
   #:block-storage-size-mib
   ;; pruning policy (prune-policy.lisp): set by the node, read here
   #:+min-blocks-to-keep+
   #:+min-disk-space-for-block-files+
   #:*prune-target-mib*
   #:*prune-after-height*
   #:pruning-enabled-p
   #:automatic-pruning-p
   #:prune-after-height
   #:prune-target-bytes
   #:prune-old-blocks
   #:prune-blocks-to-height
   ;; UTXO set
   #:utxo-set
   #:make-utxo-set
   #:utxo-entry
   #:make-utxo-entry
   #:script-unspendable-p
   #:script-has-valid-ops-p
   #:+max-script-size+
   #:any-utxo-for-txid-p
   #:utxo-entry-value
   #:utxo-entry-script-pubkey
   #:utxo-entry-height
   #:utxo-entry-coinbase
   #:add-utxo
   #:remove-utxo
   #:get-utxo
   #:utxo-exists-p
   #:utxo-count
   #:apply-block-to-utxo-set
   #:disconnect-block-from-utxo-set
   ;; Chain state
   #:chain-state
   #:make-chain-state
   #:init-chain-state
   #:network-genesis-hash
   #:make-genesis-block
   #:block-index-entry
   #:make-block-index-entry
   #:block-index-entry-hash
   #:block-index-entry-height
   #:block-index-entry-header
   #:block-index-entry-prev-entry
   #:block-index-entry-chain-work
   #:block-index-entry-status
   #:block-index-entry-tx-count
   #:block-index-entry-file
   #:block-index-entry-data-pos
   #:block-index-entry-undo-pos
   #:note-block-position
   #:%record-block-position
   #:get-block-index-entry
   #:add-block-index-entry
   #:get-block-at-height
   #:best-block-hash
   #:current-height
   #:update-chain-tip
   #:build-block-locator
   #:entry-on-active-chain-p
   #:find-fork-in-active-chain
   #:active-chain-entries-from
   #:bits-to-target
   #:derive-target
   #:target-to-bits
   #:calculate-chain-work
   #:calculate-next-work-required
   ;; Difficulty constants
   #:+difficulty-adjustment-interval+
   #:+pow-target-timespan+
   #:+pow-limit-bits+
   #:+pow-limit-target+
   #:+regtest-pow-limit-bits+
   #:+signet-pow-limit-bits+
   #:+signet-pow-limit-target+
   #:+regtest-pow-limit-target+
   #:*pow-limit-target*
   #:save-state
   #:load-state
   #:chain-state-pruned-height
   #:chain-state-prune-floor
   #:lift-prune-floor-on-promotion
   ;; Chainstate roles / assumeutxo identity (Core ChainstateManager)
   #:chain-state-coins-view
   #:chain-state-coins-cache-bytes
   #:chain-state-from-snapshot-blockhash
   #:chain-state-assumeutxo-status
   #:chain-state-target-blockhash
   #:chain-state-target-utxohash
   #:chain-state-storage-suffix
   #:select-current-chainstate
   #:select-historical-chainstate
   #:select-validated-chainstate
   #:state-file-path
   #:chainstate-leveldb-path
   ;; Target block / historical-chainstate path (Core SetTargetBlock)
   #:entry-ancestor-at-height
   #:set-chainstate-target
   #:clear-snapshot-chainstate-identity
   #:target-ancestor-entry
   #:entry-target-ancestor-p
   #:chain-state-target-height
   #:best-header-entry
   ;; Per-chainstate coins-view lifecycle
   #:open-chainstate-coins-view
   #:close-chainstate-coins-view
   ;; Snapshot chainstate on-disk marker (Core node/utxo_snapshot)
   #:snapshot-base-blockhash-path
   #:write-snapshot-base-blockhash
   #:read-snapshot-base-blockhash
   #:find-assumeutxo-chainstate-dir
   #:delete-snapshot-chainstate-files
   #:rename-snapshot-chainstate-dir-invalid
   #:promote-snapshot-chainstate-files
   ;; UTXO persistence
   #:save-utxo-set
   #:load-utxo-set
   #:utxo-set-file-path
   #:utxo-set-dirty
   ;; LevelDB CFFI bindings
   #:ensure-libleveldb-loaded
   #:leveldb-make-options
   #:leveldb-destroy-options
   #:leveldb-open
   #:leveldb-open-tuned
   #:calculate-cache-sizes
   #:cache-sizes-tx-index
   #:cache-sizes-filter-index
   #:cache-sizes-block-tree-db
   #:cache-sizes-coins-db
   #:cache-sizes-coins
   #:leveldb-close
   #:leveldb-destroy-db
   #:with-leveldb
   #:leveldb-put
   #:leveldb-get
   #:leveldb-delete
   #:leveldb-write
   #:leveldb-compact
   #:leveldb-make-writebatch
   #:leveldb-destroy-writebatch
   #:leveldb-writebatch-clear
   #:leveldb-writebatch-put
   #:leveldb-writebatch-delete
   #:with-leveldb-writebatch
   #:with-leveldb-iterator
   #:leveldb-iter-valid-p
   #:leveldb-iter-check-error
   #:leveldb-iter-seek-to-first
   #:leveldb-iter-seek
   #:leveldb-iter-next
   #:leveldb-iter-key
   #:leveldb-iter-value
   ;; Coins-view (LevelDB-backed CCoinsViewDB equivalent)
   #:coins-view-db
   #:open-coins-view-db
   #:close-coins-view-db
   #:with-coins-view-db
   #:coins-view-db-get
   #:coins-view-db-put
   #:coins-view-db-erase
   #:coins-view-db-has-p
   #:coins-view-db-write-batch
   #:with-coins-view-batch
   #:coins-view-batch-put
   #:coins-view-batch-erase
   ;; Coins-view-cache (in-memory dirty-tracking layer)
   #:coins-view-cache
   #:make-coins-view-cache
   #:coins-view-cache-compact
   #:coins-view-cache-get
   #:coins-view-cache-has-p
   #:coins-view-cache-add
   #:coins-view-cache-spend
   #:coins-view-cache-flush
   #:coins-view-cache-sync
   #:coins-view-cache-uncache
   #:with-coins-to-uncache
   #:coins-view-best-block
   #:coins-view-db-best-block
   #:coins-view-cache-load-best-block
   #:coins-view-batch-set-best-block
   #:coins-view-cache-wipe
   #:coins-view-cache-base
   #:view-mem-bytes
   ;; coin-view-* (txid+vout signatures mirroring legacy utxo-set API)
   #:coin-view-get
   #:coin-view-has-p
   #:coin-view-add
   #:coin-view-spend
   #:coin-view-any-utxo-for-txid-p
   #:coin-view-apply-block
   #:coin-view-disconnect-block
   ;; Migration: utxoset.dat → LevelDB
   #:migrate-utxoset-dat-to-leveldb
   #:leveldb-utxo-migration-complete-p
   ;; UTXO iteration and statistics
   #:utxo-set-iterate
   #:utxo-set-total-amount
   #:utxo-set-distinct-txids
   #:compute-utxo-set-hash
   #:compute-utxo-set-muhash
   #:coin-muhash-element
   #:coin-muhash-element*
   ;; coinstatsindex (per-height UTXO stats + MuHash)
   #:coinstatsindex
   #:coinstats
   #:init-coinstatsindex
   #:close-coinstatsindex
   #:coinstatsindex-db
   #:coinstatsindex-enabled
   #:coinstatsindex-height
   #:coinstatsindex-best
   #:coinstatsindex-get-stats
   #:coinstatsindex-add-block
   #:coinstatsindex-record-matches-block-p
   #:coinstatsindex-seed-genesis
   #:coinstatsindex-set-best
   #:coinstatsindex-clear-best
   #:build-coinstatsindex
   #:apply-block-to-coinstats
   #:coinstats-muhash
   #:coinstats-txout-count
   #:coinstats-bogo-size
   #:coinstats-total-amount
   #:coinstats-total-subsidy
   #:coinstats-total-prevout-spent
   #:coinstats-total-new-outputs-ex-coinbase
   #:coinstats-total-coinbase
   #:coinstats-unspendable-genesis
   #:coinstats-unspendable-bip30
   #:coinstats-unspendable-scripts
   #:coinstats-unspendable-unclaimed
   ;; Header index persistence
   #:save-header-index
   #:load-header-index
   ;; Integrity utilities
   #:compute-crc32
   #:save-file-with-crc32
   #:save-file-with-crc32-bb
   #:bb-write-utxo-entry-fields
   ;; Flat-file storage engine (flatfile.{h,cpp}, util/obfuscation.h)
   #:+blockfile-chunk-size+
   #:+undofile-chunk-size+
   #:+max-blockfile-size+
   #:+storage-header-bytes+
   #:+undo-data-disk-overhead+
   #:make-flat-file-pos
   #:flat-file-pos-file
   #:flat-file-pos-pos
   #:flat-file-pos-null-p
   #:obfuscate!
   #:obfuscation-key-active-p
   #:make-obfuscation-key
   #:zero-obfuscation-key
   #:read-or-create-xor-key
   #:make-flat-file-seq
   #:flat-file-name
   #:with-flat-file
   #:flat-file-allocate
   #:flat-file-flush
   #:flat-record-bytes
   #:undo-record-checksum
   #:undo-record-bytes
   #:parse-flat-record-header
   #:find-next-record
   ;; Core CBlockUndo record (undo.h)
   #:serialize-block-undo
   #:deserialize-block-undo
   #:block-undo-from-spent-utxos
   #:spent-utxos-from-block-undo
   #:load-file-with-crc32
   #:write-utxo-entry-fields
   #:read-utxo-entry-fields
   ;; Transaction index
   #:tx-index
   #:make-tx-index
   #:tx-index-enabled
   #:tx-location
   #:make-tx-location
   #:tx-location-block-hash
   #:tx-location-tx-position
   #:init-tx-index
   #:close-tx-index
   #:txindex-add
   #:txindex-lookup
   #:txindex-remove
   #:txindex-contains-p
   #:txindex-count
   #:txindex-set-best-block
   #:txindex-best-block
   #:txospender-index
   #:init-txospender-index
   #:close-txospender-index
   #:txospender-index-enabled
   #:txospenderindex-add-block
   #:txospenderindex-remove-block
   #:txospenderindex-locators
   #:txospenderindex-set-best-block
   #:txospenderindex-best-block
   #:txospenderindex-height
   #:txospenderindex-db-path
   #:load-tx-index
   #:txindex-add-block
   #:txindex-remove-block
   #:build-tx-index
   ;; index-base.lisp: the protocol every index implements
   #:base-index
   #:base-index-enabled
   #:base-index-db
   #:base-index-base-path
   #:index-name
   #:index-height
   #:index-best-block
   #:index-set-best
   #:index-clear-best
   #:index-write-block
   #:index-rewind-block
   #:index-prepare-sync
   #:index-sync
   ;; BIP158 block filters (basic filter)
   #:+basic-filter-type+
   #:+basic-filter-p+
   #:+basic-filter-m+
   #:build-gcs-filter
   #:gcs-filter-match
   #:gcs-filter-match-any
   #:gcs-fast-range
   #:block-filter-siphash-keys
   #:basic-filter-elements
   #:build-basic-block-filter
   #:block-filter-hash
   #:block-filter-header
   #:compute-block-filter-header
   #:+zero-filter-header+
   ;; BIP157/158 block filter index
   #:blockfilterindex
   #:make-blockfilterindex
   #:blockfilterindex-enabled
   #:blockfilterindex-db
   #:init-blockfilterindex
   #:close-blockfilterindex
   #:blockfilterindex-add-block
   #:blockfilterindex-get
   #:blockfilterindex-get-filter
   #:blockfilterindex-get-header
   #:blockfilterindex-has-block-p
   #:blockfilterindex-best
   #:blockfilterindex-height
   #:blockfilterindex-set-best
   #:blockfilterindex-clear-best
   #:blockfilterindex-wipe
   #:blockfilterindex-ensure-genesis-anchor
   #:build-blockfilterindex))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (bitcoin-lisp.nicknames:install-package-nicknames))
